# coding: utf-8

"""
    ProgrammableInbox Email Inboxes API

    Email inbox management endpoints with API key support

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from programmableinbox.models.get_email_inbox_messages200_response import GetEmailInboxMessages200Response

class TestGetEmailInboxMessages200Response(unittest.TestCase):
    """GetEmailInboxMessages200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetEmailInboxMessages200Response:
        """Test GetEmailInboxMessages200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetEmailInboxMessages200Response`
        """
        model = GetEmailInboxMessages200Response()
        if include_optional:
            return GetEmailInboxMessages200Response(
                data = programmableinbox.models.get_email_inbox_messages_200_response_data.getEmailInboxMessages_200_response_data(
                    messages = [
                        null
                        ], 
                    next_cursor = '', 
                    has_more = True, )
            )
        else:
            return GetEmailInboxMessages200Response(
                data = programmableinbox.models.get_email_inbox_messages_200_response_data.getEmailInboxMessages_200_response_data(
                    messages = [
                        null
                        ], 
                    next_cursor = '', 
                    has_more = True, ),
        )
        """

    def testGetEmailInboxMessages200Response(self):
        """Test GetEmailInboxMessages200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
