# coding: utf-8

"""
    ProgrammableInbox Email Inboxes API

    Email inbox management endpoints with API key support

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from programmableinbox.models.get_email_message200_response import GetEmailMessage200Response

class TestGetEmailMessage200Response(unittest.TestCase):
    """GetEmailMessage200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetEmailMessage200Response:
        """Test GetEmailMessage200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetEmailMessage200Response`
        """
        model = GetEmailMessage200Response()
        if include_optional:
            return GetEmailMessage200Response(
                data = programmableinbox.models.email_message.EmailMessage(
                    id = 'msg-1', 
                    thread_id = 'thread-1', 
                    parent_message_id = 'msg-0', 
                    subject = 'Support Request', 
                    from = 'customer@example.com', 
                    to = [
                        ''
                        ], 
                    cc = [
                        ''
                        ], 
                    bcc = [
                        ''
                        ], 
                    text = 'Hello, I need help with...', 
                    html = '<p>Hello, I need help with...</p>', 
                    body_text = 'Hello, I need help with...', 
                    is_starred = False, 
                    tags = [
                        ''
                        ], 
                    categories = [
                        ''
                        ], 
                    extracted_otp = '123456', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    thread_count = 56, )
            )
        else:
            return GetEmailMessage200Response(
                data = programmableinbox.models.email_message.EmailMessage(
                    id = 'msg-1', 
                    thread_id = 'thread-1', 
                    parent_message_id = 'msg-0', 
                    subject = 'Support Request', 
                    from = 'customer@example.com', 
                    to = [
                        ''
                        ], 
                    cc = [
                        ''
                        ], 
                    bcc = [
                        ''
                        ], 
                    text = 'Hello, I need help with...', 
                    html = '<p>Hello, I need help with...</p>', 
                    body_text = 'Hello, I need help with...', 
                    is_starred = False, 
                    tags = [
                        ''
                        ], 
                    categories = [
                        ''
                        ], 
                    extracted_otp = '123456', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    thread_count = 56, ),
        )
        """

    def testGetEmailMessage200Response(self):
        """Test GetEmailMessage200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
