# coding: utf-8

"""
    ProgrammableInbox Email Inboxes API

    Email inbox management endpoints with API key support

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from programmableinbox.models.email_message import EmailMessage

class TestEmailMessage(unittest.TestCase):
    """EmailMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EmailMessage:
        """Test EmailMessage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EmailMessage`
        """
        model = EmailMessage()
        if include_optional:
            return EmailMessage(
                id = 'msg-1',
                thread_id = 'thread-1',
                parent_message_id = 'msg-0',
                subject = 'Support Request',
                var_from = 'customer@example.com',
                to = [
                    ''
                    ],
                cc = [
                    ''
                    ],
                bcc = [
                    ''
                    ],
                text = 'Hello, I need help with...',
                html = '<p>Hello, I need help with...</p>',
                body_text = 'Hello, I need help with...',
                is_starred = False,
                tags = [
                    ''
                    ],
                categories = [
                    ''
                    ],
                extracted_otp = '123456',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                thread_count = 56
            )
        else:
            return EmailMessage(
                id = 'msg-1',
                thread_id = 'thread-1',
                parent_message_id = 'msg-0',
                subject = 'Support Request',
                var_from = 'customer@example.com',
                to = [
                    ''
                    ],
                cc = [
                    ''
                    ],
                bcc = [
                    ''
                    ],
                text = 'Hello, I need help with...',
                html = '<p>Hello, I need help with...</p>',
                body_text = 'Hello, I need help with...',
                is_starred = False,
                tags = [
                    ''
                    ],
                categories = [
                    ''
                    ],
                extracted_otp = '123456',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testEmailMessage(self):
        """Test EmailMessage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
