# coding: utf-8

"""
    ProgrammableInbox Email Inboxes API

    Email inbox management endpoints with API key support

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from programmableinbox.models.get_email_inbox200_response import GetEmailInbox200Response

class TestGetEmailInbox200Response(unittest.TestCase):
    """GetEmailInbox200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetEmailInbox200Response:
        """Test GetEmailInbox200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetEmailInbox200Response`
        """
        model = GetEmailInbox200Response()
        if include_optional:
            return GetEmailInbox200Response(
                data = programmableinbox.models.email_inbox.EmailInbox(
                    id = 'inbox-1', 
                    organization_id = 'org-1', 
                    email = 'support@example.com', 
                    name = 'Support Inbox', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return GetEmailInbox200Response(
        )
        """

    def testGetEmailInbox200Response(self):
        """Test GetEmailInbox200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
