# coding: utf-8

"""
    ProgrammableInbox Email Inboxes API

    Email inbox management endpoints with API key support

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from programmableinbox.api.email_inboxes_api import EmailInboxesApi


class TestEmailInboxesApi(unittest.TestCase):
    """EmailInboxesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EmailInboxesApi()

    def tearDown(self) -> None:
        pass

    def test_create_email_inbox(self) -> None:
        """Test case for create_email_inbox

        Create an email inbox
        """
        pass

    def test_delete_email_inbox(self) -> None:
        """Test case for delete_email_inbox

        Delete an email inbox
        """
        pass

    def test_get_email_inbox(self) -> None:
        """Test case for get_email_inbox

        Get an email inbox
        """
        pass

    def test_get_email_inbox_messages(self) -> None:
        """Test case for get_email_inbox_messages

        Get messages from an email inbox
        """
        pass

    def test_get_email_message(self) -> None:
        """Test case for get_email_message

        Get a single message
        """
        pass

    def test_list_email_inboxes(self) -> None:
        """Test case for list_email_inboxes

        List email inboxes
        """
        pass

    def test_update_email_inbox(self) -> None:
        """Test case for update_email_inbox

        Rename an email inbox
        """
        pass


if __name__ == '__main__':
    unittest.main()
