/*
 * ProgrammableInbox Email Inboxes API
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.programmableinbox.sdk.api;

import com.programmableinbox.sdk.ApiClient;
import com.programmableinbox.sdk.ApiException;
import com.programmableinbox.sdk.ApiResponse;
import com.programmableinbox.sdk.Configuration;
import com.programmableinbox.sdk.Pair;

import com.programmableinbox.sdk.model.CreateEmailInbox201Response;
import com.programmableinbox.sdk.model.CreateEmailInboxRequest;
import com.programmableinbox.sdk.model.ErrorResponse;
import com.programmableinbox.sdk.model.GetEmailInbox200Response;
import com.programmableinbox.sdk.model.GetEmailInboxMessages200Response;
import com.programmableinbox.sdk.model.GetEmailInboxOtp200Response;
import com.programmableinbox.sdk.model.GetEmailMessage200Response;
import com.programmableinbox.sdk.model.ListEmailInboxes200Response;
import com.programmableinbox.sdk.model.UpdateEmailInboxRequest;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class EmailInboxesApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public EmailInboxesApi() {
    this(Configuration.getDefaultApiClient());
  }

  public EmailInboxesApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Create an email inbox
   * Claims a new email address and returns the inbox. The address must be on a domain this account can receive at, and is immutable once created. Requires API key with &#x60;email_inboxes:create&#x60; scope. The inbox is created in the organization the key is bound to; supplying a different &#x60;organizationId&#x60; is a 403 rather than a silently ignored field.
   * @param createEmailInboxRequest  (required)
   * @return CreateEmailInbox201Response
   * @throws ApiException if fails to make API call
   */
  public CreateEmailInbox201Response createEmailInbox(@javax.annotation.Nonnull CreateEmailInboxRequest createEmailInboxRequest) throws ApiException {
    return createEmailInbox(createEmailInboxRequest, null);
  }

  /**
   * Create an email inbox
   * Claims a new email address and returns the inbox. The address must be on a domain this account can receive at, and is immutable once created. Requires API key with &#x60;email_inboxes:create&#x60; scope. The inbox is created in the organization the key is bound to; supplying a different &#x60;organizationId&#x60; is a 403 rather than a silently ignored field.
   * @param createEmailInboxRequest  (required)
   * @param headers Optional headers to include in the request
   * @return CreateEmailInbox201Response
   * @throws ApiException if fails to make API call
   */
  public CreateEmailInbox201Response createEmailInbox(@javax.annotation.Nonnull CreateEmailInboxRequest createEmailInboxRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<CreateEmailInbox201Response> localVarResponse = createEmailInboxWithHttpInfo(createEmailInboxRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Create an email inbox
   * Claims a new email address and returns the inbox. The address must be on a domain this account can receive at, and is immutable once created. Requires API key with &#x60;email_inboxes:create&#x60; scope. The inbox is created in the organization the key is bound to; supplying a different &#x60;organizationId&#x60; is a 403 rather than a silently ignored field.
   * @param createEmailInboxRequest  (required)
   * @return ApiResponse&lt;CreateEmailInbox201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateEmailInbox201Response> createEmailInboxWithHttpInfo(@javax.annotation.Nonnull CreateEmailInboxRequest createEmailInboxRequest) throws ApiException {
    return createEmailInboxWithHttpInfo(createEmailInboxRequest, null);
  }

  /**
   * Create an email inbox
   * Claims a new email address and returns the inbox. The address must be on a domain this account can receive at, and is immutable once created. Requires API key with &#x60;email_inboxes:create&#x60; scope. The inbox is created in the organization the key is bound to; supplying a different &#x60;organizationId&#x60; is a 403 rather than a silently ignored field.
   * @param createEmailInboxRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CreateEmailInbox201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateEmailInbox201Response> createEmailInboxWithHttpInfo(@javax.annotation.Nonnull CreateEmailInboxRequest createEmailInboxRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createEmailInboxRequestBuilder(createEmailInboxRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createEmailInbox", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CreateEmailInbox201Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CreateEmailInbox201Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CreateEmailInbox201Response>() {});
        

        return new ApiResponse<CreateEmailInbox201Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createEmailInboxRequestBuilder(@javax.annotation.Nonnull CreateEmailInboxRequest createEmailInboxRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'createEmailInboxRequest' is set
    if (createEmailInboxRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'createEmailInboxRequest' when calling createEmailInbox");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/emailInbox";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(createEmailInboxRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete an email inbox
   * Soft-deletes the inbox and its messages in one transaction. The rows are retained and every read filters them out, so the data is recoverable — but the **address is retired permanently and can never be claimed again, by anyone including you**. Mail keeps being delivered to it, so releasing it would hand the next claimant your still-arriving messages. Requires API key with &#x60;email_inboxes:delete&#x60; scope, which is granted separately from create and update for exactly this reason.
   * @param id The email inbox ID (required)
   * @throws ApiException if fails to make API call
   */
  public void deleteEmailInbox(@javax.annotation.Nonnull String id) throws ApiException {
    deleteEmailInbox(id, null);
  }

  /**
   * Delete an email inbox
   * Soft-deletes the inbox and its messages in one transaction. The rows are retained and every read filters them out, so the data is recoverable — but the **address is retired permanently and can never be claimed again, by anyone including you**. Mail keeps being delivered to it, so releasing it would hand the next claimant your still-arriving messages. Requires API key with &#x60;email_inboxes:delete&#x60; scope, which is granted separately from create and update for exactly this reason.
   * @param id The email inbox ID (required)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void deleteEmailInbox(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    deleteEmailInboxWithHttpInfo(id, headers);
  }

  /**
   * Delete an email inbox
   * Soft-deletes the inbox and its messages in one transaction. The rows are retained and every read filters them out, so the data is recoverable — but the **address is retired permanently and can never be claimed again, by anyone including you**. Mail keeps being delivered to it, so releasing it would hand the next claimant your still-arriving messages. Requires API key with &#x60;email_inboxes:delete&#x60; scope, which is granted separately from create and update for exactly this reason.
   * @param id The email inbox ID (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deleteEmailInboxWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
    return deleteEmailInboxWithHttpInfo(id, null);
  }

  /**
   * Delete an email inbox
   * Soft-deletes the inbox and its messages in one transaction. The rows are retained and every read filters them out, so the data is recoverable — but the **address is retired permanently and can never be claimed again, by anyone including you**. Mail keeps being delivered to it, so releasing it would hand the next claimant your still-arriving messages. Requires API key with &#x60;email_inboxes:delete&#x60; scope, which is granted separately from create and update for exactly this reason.
   * @param id The email inbox ID (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deleteEmailInboxWithHttpInfo(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteEmailInboxRequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteEmailInbox", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody != null) {
          localVarResponseBody.readAllBytes();
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteEmailInboxRequestBuilder(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling deleteEmailInbox");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/emailInbox/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get an email inbox
   * Returns a single email inbox by id, scoped to the organization the API key is bound to. Requires API key with &#x60;email_inboxes:read&#x60; scope.
   * @param id Email inbox ID (required)
   * @return GetEmailInbox200Response
   * @throws ApiException if fails to make API call
   */
  public GetEmailInbox200Response getEmailInbox(@javax.annotation.Nonnull String id) throws ApiException {
    return getEmailInbox(id, null);
  }

  /**
   * Get an email inbox
   * Returns a single email inbox by id, scoped to the organization the API key is bound to. Requires API key with &#x60;email_inboxes:read&#x60; scope.
   * @param id Email inbox ID (required)
   * @param headers Optional headers to include in the request
   * @return GetEmailInbox200Response
   * @throws ApiException if fails to make API call
   */
  public GetEmailInbox200Response getEmailInbox(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    ApiResponse<GetEmailInbox200Response> localVarResponse = getEmailInboxWithHttpInfo(id, headers);
    return localVarResponse.getData();
  }

  /**
   * Get an email inbox
   * Returns a single email inbox by id, scoped to the organization the API key is bound to. Requires API key with &#x60;email_inboxes:read&#x60; scope.
   * @param id Email inbox ID (required)
   * @return ApiResponse&lt;GetEmailInbox200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetEmailInbox200Response> getEmailInboxWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
    return getEmailInboxWithHttpInfo(id, null);
  }

  /**
   * Get an email inbox
   * Returns a single email inbox by id, scoped to the organization the API key is bound to. Requires API key with &#x60;email_inboxes:read&#x60; scope.
   * @param id Email inbox ID (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;GetEmailInbox200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetEmailInbox200Response> getEmailInboxWithHttpInfo(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getEmailInboxRequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getEmailInbox", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<GetEmailInbox200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        GetEmailInbox200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<GetEmailInbox200Response>() {});
        

        return new ApiResponse<GetEmailInbox200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getEmailInboxRequestBuilder(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getEmailInbox");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/emailInbox/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get messages from an email inbox
   * Returns messages for a specific email inbox with optional pagination and filtering. Requires API key with &#x60;email_messages:read&#x60; scope.
   * @param id The email inbox ID (required)
   * @param cursor Opaque pagination cursor from a previous response&#39;s nextCursor. Omit for the first page. (optional)
   * @param limit Number of messages per page (default: 50, max: 100) (optional)
   * @param threadId Optional thread ID to filter messages to a specific thread (optional)
   * @param grouped If true, returns only the latest message per thread (grouped view). Cannot be combined with any search parameter — the combination returns 400. (optional)
   * @param q Full-text search over the subject and the message body. Supports \&quot;quoted phrases\&quot;, &#x60;or&#x60;, and &#x60;-negation&#x60; (Postgres websearch syntax). The body searched is the plain-text &#x60;bodyText&#x60; field, which is extracted from &#x60;html&#x60; for messages that carry no text part. Results stay in reverse-chronological order — this filters, it does not rank. (optional)
   * @param from Case-insensitive substring match on the sender. Matches the raw header, so it covers both the display name and the address. (optional)
   * @param tags Return messages carrying any of these tags (exact match, OR-combined). Repeat the parameter: tags&#x3D;a&amp;tags&#x3D;b. A comma-separated single value (tags&#x3D;a,b) is also accepted, but cannot express a tag that itself contains a comma. Max 20 values. (optional)
   * @param categories Return messages carrying any of these categories (exact match, OR-combined). Repeat the parameter: categories&#x3D;a&amp;categories&#x3D;b. A comma-separated single value is also accepted, but cannot express a category that itself contains a comma. Max 20 values. (optional)
   * @return GetEmailInboxMessages200Response
   * @throws ApiException if fails to make API call
   */
  public GetEmailInboxMessages200Response getEmailInboxMessages(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String threadId, @javax.annotation.Nullable Boolean grouped, @javax.annotation.Nullable String q, @javax.annotation.Nullable String from, @javax.annotation.Nullable List<String> tags, @javax.annotation.Nullable List<String> categories) throws ApiException {
    return getEmailInboxMessages(id, cursor, limit, threadId, grouped, q, from, tags, categories, null);
  }

  /**
   * Get messages from an email inbox
   * Returns messages for a specific email inbox with optional pagination and filtering. Requires API key with &#x60;email_messages:read&#x60; scope.
   * @param id The email inbox ID (required)
   * @param cursor Opaque pagination cursor from a previous response&#39;s nextCursor. Omit for the first page. (optional)
   * @param limit Number of messages per page (default: 50, max: 100) (optional)
   * @param threadId Optional thread ID to filter messages to a specific thread (optional)
   * @param grouped If true, returns only the latest message per thread (grouped view). Cannot be combined with any search parameter — the combination returns 400. (optional)
   * @param q Full-text search over the subject and the message body. Supports \&quot;quoted phrases\&quot;, &#x60;or&#x60;, and &#x60;-negation&#x60; (Postgres websearch syntax). The body searched is the plain-text &#x60;bodyText&#x60; field, which is extracted from &#x60;html&#x60; for messages that carry no text part. Results stay in reverse-chronological order — this filters, it does not rank. (optional)
   * @param from Case-insensitive substring match on the sender. Matches the raw header, so it covers both the display name and the address. (optional)
   * @param tags Return messages carrying any of these tags (exact match, OR-combined). Repeat the parameter: tags&#x3D;a&amp;tags&#x3D;b. A comma-separated single value (tags&#x3D;a,b) is also accepted, but cannot express a tag that itself contains a comma. Max 20 values. (optional)
   * @param categories Return messages carrying any of these categories (exact match, OR-combined). Repeat the parameter: categories&#x3D;a&amp;categories&#x3D;b. A comma-separated single value is also accepted, but cannot express a category that itself contains a comma. Max 20 values. (optional)
   * @param headers Optional headers to include in the request
   * @return GetEmailInboxMessages200Response
   * @throws ApiException if fails to make API call
   */
  public GetEmailInboxMessages200Response getEmailInboxMessages(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String threadId, @javax.annotation.Nullable Boolean grouped, @javax.annotation.Nullable String q, @javax.annotation.Nullable String from, @javax.annotation.Nullable List<String> tags, @javax.annotation.Nullable List<String> categories, Map<String, String> headers) throws ApiException {
    ApiResponse<GetEmailInboxMessages200Response> localVarResponse = getEmailInboxMessagesWithHttpInfo(id, cursor, limit, threadId, grouped, q, from, tags, categories, headers);
    return localVarResponse.getData();
  }

  /**
   * Get messages from an email inbox
   * Returns messages for a specific email inbox with optional pagination and filtering. Requires API key with &#x60;email_messages:read&#x60; scope.
   * @param id The email inbox ID (required)
   * @param cursor Opaque pagination cursor from a previous response&#39;s nextCursor. Omit for the first page. (optional)
   * @param limit Number of messages per page (default: 50, max: 100) (optional)
   * @param threadId Optional thread ID to filter messages to a specific thread (optional)
   * @param grouped If true, returns only the latest message per thread (grouped view). Cannot be combined with any search parameter — the combination returns 400. (optional)
   * @param q Full-text search over the subject and the message body. Supports \&quot;quoted phrases\&quot;, &#x60;or&#x60;, and &#x60;-negation&#x60; (Postgres websearch syntax). The body searched is the plain-text &#x60;bodyText&#x60; field, which is extracted from &#x60;html&#x60; for messages that carry no text part. Results stay in reverse-chronological order — this filters, it does not rank. (optional)
   * @param from Case-insensitive substring match on the sender. Matches the raw header, so it covers both the display name and the address. (optional)
   * @param tags Return messages carrying any of these tags (exact match, OR-combined). Repeat the parameter: tags&#x3D;a&amp;tags&#x3D;b. A comma-separated single value (tags&#x3D;a,b) is also accepted, but cannot express a tag that itself contains a comma. Max 20 values. (optional)
   * @param categories Return messages carrying any of these categories (exact match, OR-combined). Repeat the parameter: categories&#x3D;a&amp;categories&#x3D;b. A comma-separated single value is also accepted, but cannot express a category that itself contains a comma. Max 20 values. (optional)
   * @return ApiResponse&lt;GetEmailInboxMessages200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetEmailInboxMessages200Response> getEmailInboxMessagesWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String threadId, @javax.annotation.Nullable Boolean grouped, @javax.annotation.Nullable String q, @javax.annotation.Nullable String from, @javax.annotation.Nullable List<String> tags, @javax.annotation.Nullable List<String> categories) throws ApiException {
    return getEmailInboxMessagesWithHttpInfo(id, cursor, limit, threadId, grouped, q, from, tags, categories, null);
  }

  /**
   * Get messages from an email inbox
   * Returns messages for a specific email inbox with optional pagination and filtering. Requires API key with &#x60;email_messages:read&#x60; scope.
   * @param id The email inbox ID (required)
   * @param cursor Opaque pagination cursor from a previous response&#39;s nextCursor. Omit for the first page. (optional)
   * @param limit Number of messages per page (default: 50, max: 100) (optional)
   * @param threadId Optional thread ID to filter messages to a specific thread (optional)
   * @param grouped If true, returns only the latest message per thread (grouped view). Cannot be combined with any search parameter — the combination returns 400. (optional)
   * @param q Full-text search over the subject and the message body. Supports \&quot;quoted phrases\&quot;, &#x60;or&#x60;, and &#x60;-negation&#x60; (Postgres websearch syntax). The body searched is the plain-text &#x60;bodyText&#x60; field, which is extracted from &#x60;html&#x60; for messages that carry no text part. Results stay in reverse-chronological order — this filters, it does not rank. (optional)
   * @param from Case-insensitive substring match on the sender. Matches the raw header, so it covers both the display name and the address. (optional)
   * @param tags Return messages carrying any of these tags (exact match, OR-combined). Repeat the parameter: tags&#x3D;a&amp;tags&#x3D;b. A comma-separated single value (tags&#x3D;a,b) is also accepted, but cannot express a tag that itself contains a comma. Max 20 values. (optional)
   * @param categories Return messages carrying any of these categories (exact match, OR-combined). Repeat the parameter: categories&#x3D;a&amp;categories&#x3D;b. A comma-separated single value is also accepted, but cannot express a category that itself contains a comma. Max 20 values. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;GetEmailInboxMessages200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetEmailInboxMessages200Response> getEmailInboxMessagesWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String threadId, @javax.annotation.Nullable Boolean grouped, @javax.annotation.Nullable String q, @javax.annotation.Nullable String from, @javax.annotation.Nullable List<String> tags, @javax.annotation.Nullable List<String> categories, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getEmailInboxMessagesRequestBuilder(id, cursor, limit, threadId, grouped, q, from, tags, categories, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getEmailInboxMessages", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<GetEmailInboxMessages200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        GetEmailInboxMessages200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<GetEmailInboxMessages200Response>() {});
        

        return new ApiResponse<GetEmailInboxMessages200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getEmailInboxMessagesRequestBuilder(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String threadId, @javax.annotation.Nullable Boolean grouped, @javax.annotation.Nullable String q, @javax.annotation.Nullable String from, @javax.annotation.Nullable List<String> tags, @javax.annotation.Nullable List<String> categories, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getEmailInboxMessages");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/emailInbox/{id}/messages"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "cursor";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("cursor", cursor));
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));
    localVarQueryParameterBaseName = "threadId";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("threadId", threadId));
    localVarQueryParameterBaseName = "grouped";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("grouped", grouped));
    localVarQueryParameterBaseName = "q";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("q", q));
    localVarQueryParameterBaseName = "from";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("from", from));
    localVarQueryParameterBaseName = "tags";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("multi", "tags", tags));
    localVarQueryParameterBaseName = "categories";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("multi", "categories", categories));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get the latest one-time code for an inbox
   * Returns the most recently extracted one-time passcode (OTP) for an email inbox, with the message it came from. Requires API key with &#x60;email_messages:read&#x60; scope — this is a read of extracted message content, not inbox metadata.
   * @param id The email inbox ID (required)
   * @return GetEmailInboxOtp200Response
   * @throws ApiException if fails to make API call
   */
  public GetEmailInboxOtp200Response getEmailInboxOtp(@javax.annotation.Nonnull String id) throws ApiException {
    return getEmailInboxOtp(id, null);
  }

  /**
   * Get the latest one-time code for an inbox
   * Returns the most recently extracted one-time passcode (OTP) for an email inbox, with the message it came from. Requires API key with &#x60;email_messages:read&#x60; scope — this is a read of extracted message content, not inbox metadata.
   * @param id The email inbox ID (required)
   * @param headers Optional headers to include in the request
   * @return GetEmailInboxOtp200Response
   * @throws ApiException if fails to make API call
   */
  public GetEmailInboxOtp200Response getEmailInboxOtp(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    ApiResponse<GetEmailInboxOtp200Response> localVarResponse = getEmailInboxOtpWithHttpInfo(id, headers);
    return localVarResponse.getData();
  }

  /**
   * Get the latest one-time code for an inbox
   * Returns the most recently extracted one-time passcode (OTP) for an email inbox, with the message it came from. Requires API key with &#x60;email_messages:read&#x60; scope — this is a read of extracted message content, not inbox metadata.
   * @param id The email inbox ID (required)
   * @return ApiResponse&lt;GetEmailInboxOtp200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetEmailInboxOtp200Response> getEmailInboxOtpWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
    return getEmailInboxOtpWithHttpInfo(id, null);
  }

  /**
   * Get the latest one-time code for an inbox
   * Returns the most recently extracted one-time passcode (OTP) for an email inbox, with the message it came from. Requires API key with &#x60;email_messages:read&#x60; scope — this is a read of extracted message content, not inbox metadata.
   * @param id The email inbox ID (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;GetEmailInboxOtp200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetEmailInboxOtp200Response> getEmailInboxOtpWithHttpInfo(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getEmailInboxOtpRequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getEmailInboxOtp", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<GetEmailInboxOtp200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        GetEmailInboxOtp200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<GetEmailInboxOtp200Response>() {});
        

        return new ApiResponse<GetEmailInboxOtp200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getEmailInboxOtpRequestBuilder(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getEmailInboxOtp");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/emailInbox/{id}/otp"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get a single message
   * Returns a specific message from an email inbox. Requires API key with &#x60;email_messages:read&#x60; scope.
   * @param id The email inbox ID (required)
   * @param messageId The message ID (required)
   * @return GetEmailMessage200Response
   * @throws ApiException if fails to make API call
   */
  public GetEmailMessage200Response getEmailMessage(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String messageId) throws ApiException {
    return getEmailMessage(id, messageId, null);
  }

  /**
   * Get a single message
   * Returns a specific message from an email inbox. Requires API key with &#x60;email_messages:read&#x60; scope.
   * @param id The email inbox ID (required)
   * @param messageId The message ID (required)
   * @param headers Optional headers to include in the request
   * @return GetEmailMessage200Response
   * @throws ApiException if fails to make API call
   */
  public GetEmailMessage200Response getEmailMessage(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String messageId, Map<String, String> headers) throws ApiException {
    ApiResponse<GetEmailMessage200Response> localVarResponse = getEmailMessageWithHttpInfo(id, messageId, headers);
    return localVarResponse.getData();
  }

  /**
   * Get a single message
   * Returns a specific message from an email inbox. Requires API key with &#x60;email_messages:read&#x60; scope.
   * @param id The email inbox ID (required)
   * @param messageId The message ID (required)
   * @return ApiResponse&lt;GetEmailMessage200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetEmailMessage200Response> getEmailMessageWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String messageId) throws ApiException {
    return getEmailMessageWithHttpInfo(id, messageId, null);
  }

  /**
   * Get a single message
   * Returns a specific message from an email inbox. Requires API key with &#x60;email_messages:read&#x60; scope.
   * @param id The email inbox ID (required)
   * @param messageId The message ID (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;GetEmailMessage200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetEmailMessage200Response> getEmailMessageWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String messageId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getEmailMessageRequestBuilder(id, messageId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getEmailMessage", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<GetEmailMessage200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        GetEmailMessage200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<GetEmailMessage200Response>() {});
        

        return new ApiResponse<GetEmailMessage200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getEmailMessageRequestBuilder(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull String messageId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getEmailMessage");
    }
    // verify the required parameter 'messageId' is set
    if (messageId == null) {
      throw new ApiException(400, "Missing the required parameter 'messageId' when calling getEmailMessage");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/emailInbox/{id}/messages/{messageId}"
        .replace("{id}", ApiClient.urlEncode(id.toString()))
        .replace("{messageId}", ApiClient.urlEncode(messageId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List email inboxes
   * Returns a list of email inboxes for the organization. Requires API key with &#x60;email_inboxes:read&#x60; scope.
   * @return ListEmailInboxes200Response
   * @throws ApiException if fails to make API call
   */
  public ListEmailInboxes200Response listEmailInboxes() throws ApiException {
    return listEmailInboxes(null);
  }

  /**
   * List email inboxes
   * Returns a list of email inboxes for the organization. Requires API key with &#x60;email_inboxes:read&#x60; scope.
   * @param headers Optional headers to include in the request
   * @return ListEmailInboxes200Response
   * @throws ApiException if fails to make API call
   */
  public ListEmailInboxes200Response listEmailInboxes(Map<String, String> headers) throws ApiException {
    ApiResponse<ListEmailInboxes200Response> localVarResponse = listEmailInboxesWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * List email inboxes
   * Returns a list of email inboxes for the organization. Requires API key with &#x60;email_inboxes:read&#x60; scope.
   * @return ApiResponse&lt;ListEmailInboxes200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ListEmailInboxes200Response> listEmailInboxesWithHttpInfo() throws ApiException {
    return listEmailInboxesWithHttpInfo(null);
  }

  /**
   * List email inboxes
   * Returns a list of email inboxes for the organization. Requires API key with &#x60;email_inboxes:read&#x60; scope.
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ListEmailInboxes200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ListEmailInboxes200Response> listEmailInboxesWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listEmailInboxesRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listEmailInboxes", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ListEmailInboxes200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ListEmailInboxes200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ListEmailInboxes200Response>() {});
        

        return new ApiResponse<ListEmailInboxes200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listEmailInboxesRequestBuilder(Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/emailInbox";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Rename an email inbox
   * Updates an inbox display name. The address is immutable — submitting a different one is a 409; submitting the current one (after normalization) is an allowed no-op, so a client can PATCH a whole record back. Requires API key with &#x60;email_inboxes:update&#x60; scope.
   * @param id The email inbox ID (required)
   * @param updateEmailInboxRequest  (required)
   * @return CreateEmailInbox201Response
   * @throws ApiException if fails to make API call
   */
  public CreateEmailInbox201Response updateEmailInbox(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull UpdateEmailInboxRequest updateEmailInboxRequest) throws ApiException {
    return updateEmailInbox(id, updateEmailInboxRequest, null);
  }

  /**
   * Rename an email inbox
   * Updates an inbox display name. The address is immutable — submitting a different one is a 409; submitting the current one (after normalization) is an allowed no-op, so a client can PATCH a whole record back. Requires API key with &#x60;email_inboxes:update&#x60; scope.
   * @param id The email inbox ID (required)
   * @param updateEmailInboxRequest  (required)
   * @param headers Optional headers to include in the request
   * @return CreateEmailInbox201Response
   * @throws ApiException if fails to make API call
   */
  public CreateEmailInbox201Response updateEmailInbox(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull UpdateEmailInboxRequest updateEmailInboxRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<CreateEmailInbox201Response> localVarResponse = updateEmailInboxWithHttpInfo(id, updateEmailInboxRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Rename an email inbox
   * Updates an inbox display name. The address is immutable — submitting a different one is a 409; submitting the current one (after normalization) is an allowed no-op, so a client can PATCH a whole record back. Requires API key with &#x60;email_inboxes:update&#x60; scope.
   * @param id The email inbox ID (required)
   * @param updateEmailInboxRequest  (required)
   * @return ApiResponse&lt;CreateEmailInbox201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateEmailInbox201Response> updateEmailInboxWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull UpdateEmailInboxRequest updateEmailInboxRequest) throws ApiException {
    return updateEmailInboxWithHttpInfo(id, updateEmailInboxRequest, null);
  }

  /**
   * Rename an email inbox
   * Updates an inbox display name. The address is immutable — submitting a different one is a 409; submitting the current one (after normalization) is an allowed no-op, so a client can PATCH a whole record back. Requires API key with &#x60;email_inboxes:update&#x60; scope.
   * @param id The email inbox ID (required)
   * @param updateEmailInboxRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CreateEmailInbox201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateEmailInbox201Response> updateEmailInboxWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull UpdateEmailInboxRequest updateEmailInboxRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = updateEmailInboxRequestBuilder(id, updateEmailInboxRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("updateEmailInbox", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CreateEmailInbox201Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CreateEmailInbox201Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CreateEmailInbox201Response>() {});
        

        return new ApiResponse<CreateEmailInbox201Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder updateEmailInboxRequestBuilder(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull UpdateEmailInboxRequest updateEmailInboxRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling updateEmailInbox");
    }
    // verify the required parameter 'updateEmailInboxRequest' is set
    if (updateEmailInboxRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'updateEmailInboxRequest' when calling updateEmailInbox");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/emailInbox/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(updateEmailInboxRequest);
      localVarRequestBuilder.method("PATCH", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
