/*
ProgrammableInbox Email Inboxes API

Email inbox management endpoints with API key support

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package programmableinbox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateEmailInbox201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateEmailInbox201Response{}

// CreateEmailInbox201Response struct for CreateEmailInbox201Response
type CreateEmailInbox201Response struct {
	Data EmailInbox `json:"data"`
}

type _CreateEmailInbox201Response CreateEmailInbox201Response

// NewCreateEmailInbox201Response instantiates a new CreateEmailInbox201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEmailInbox201Response(data EmailInbox) *CreateEmailInbox201Response {
	this := CreateEmailInbox201Response{}
	this.Data = data
	return &this
}

// NewCreateEmailInbox201ResponseWithDefaults instantiates a new CreateEmailInbox201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEmailInbox201ResponseWithDefaults() *CreateEmailInbox201Response {
	this := CreateEmailInbox201Response{}
	return &this
}

// GetData returns the Data field value
func (o *CreateEmailInbox201Response) GetData() EmailInbox {
	if o == nil {
		var ret EmailInbox
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateEmailInbox201Response) GetDataOk() (*EmailInbox, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateEmailInbox201Response) SetData(v EmailInbox) {
	o.Data = v
}

func (o CreateEmailInbox201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateEmailInbox201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreateEmailInbox201Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateEmailInbox201Response := _CreateEmailInbox201Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateEmailInbox201Response)

	if err != nil {
		return err
	}

	*o = CreateEmailInbox201Response(varCreateEmailInbox201Response)

	return err
}

type NullableCreateEmailInbox201Response struct {
	value *CreateEmailInbox201Response
	isSet bool
}

func (v NullableCreateEmailInbox201Response) Get() *CreateEmailInbox201Response {
	return v.value
}

func (v *NullableCreateEmailInbox201Response) Set(val *CreateEmailInbox201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEmailInbox201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEmailInbox201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEmailInbox201Response(val *CreateEmailInbox201Response) *NullableCreateEmailInbox201Response {
	return &NullableCreateEmailInbox201Response{value: val, isSet: true}
}

func (v NullableCreateEmailInbox201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEmailInbox201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


