/*
ProgrammableInbox Email Inboxes API

Email inbox management endpoints with API key support

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package programmableinbox

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the EmailMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailMessage{}

// EmailMessage An email message
type EmailMessage struct {
	Id string `json:"id"`
	ThreadId string `json:"threadId"`
	ParentMessageId NullableString `json:"parentMessageId"`
	Subject string `json:"subject"`
	From string `json:"from"`
	To []string `json:"to"`
	Cc []string `json:"cc"`
	Bcc []string `json:"bcc"`
	Text string `json:"text"`
	Html string `json:"html"`
	// Plain text of the body, and the field the `q` parameter searches. Equal to `text` when the sender supplied a text part, otherwise extracted from `html`. Null for messages stored before this field existed.
	BodyText NullableString `json:"bodyText"`
	IsStarred bool `json:"isStarred"`
	// Inbox-wide, not per-user: one shared flag reflecting whether any viewer has opened this message.
	IsRead bool `json:"isRead"`
	Tags []string `json:"tags"`
	// Categories assigned to the message. Matched by the `categories` parameter.
	Categories []string `json:"categories"`
	// One-time code parsed from the message body. Derived from text/html, which the same email_messages:read scope already returns.
	ExtractedOtp NullableString `json:"extractedOtp"`
	CreatedAt time.Time `json:"createdAt"`
	// Number of messages in the thread (present only in grouped mode)
	ThreadCount *int32 `json:"threadCount,omitempty"`
}

type _EmailMessage EmailMessage

// NewEmailMessage instantiates a new EmailMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailMessage(id string, threadId string, parentMessageId NullableString, subject string, from string, to []string, cc []string, bcc []string, text string, html string, bodyText NullableString, isStarred bool, isRead bool, tags []string, categories []string, extractedOtp NullableString, createdAt time.Time) *EmailMessage {
	this := EmailMessage{}
	this.Id = id
	this.ThreadId = threadId
	this.ParentMessageId = parentMessageId
	this.Subject = subject
	this.From = from
	this.To = to
	this.Cc = cc
	this.Bcc = bcc
	this.Text = text
	this.Html = html
	this.BodyText = bodyText
	this.IsStarred = isStarred
	this.IsRead = isRead
	this.Tags = tags
	this.Categories = categories
	this.ExtractedOtp = extractedOtp
	this.CreatedAt = createdAt
	return &this
}

// NewEmailMessageWithDefaults instantiates a new EmailMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailMessageWithDefaults() *EmailMessage {
	this := EmailMessage{}
	return &this
}

// GetId returns the Id field value
func (o *EmailMessage) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *EmailMessage) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EmailMessage) SetId(v string) {
	o.Id = v
}

// GetThreadId returns the ThreadId field value
func (o *EmailMessage) GetThreadId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ThreadId
}

// GetThreadIdOk returns a tuple with the ThreadId field value
// and a boolean to check if the value has been set.
func (o *EmailMessage) GetThreadIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ThreadId, true
}

// SetThreadId sets field value
func (o *EmailMessage) SetThreadId(v string) {
	o.ThreadId = v
}

// GetParentMessageId returns the ParentMessageId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *EmailMessage) GetParentMessageId() string {
	if o == nil || o.ParentMessageId.Get() == nil {
		var ret string
		return ret
	}

	return *o.ParentMessageId.Get()
}

// GetParentMessageIdOk returns a tuple with the ParentMessageId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailMessage) GetParentMessageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentMessageId.Get(), o.ParentMessageId.IsSet()
}

// SetParentMessageId sets field value
func (o *EmailMessage) SetParentMessageId(v string) {
	o.ParentMessageId.Set(&v)
}

// GetSubject returns the Subject field value
func (o *EmailMessage) GetSubject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value
// and a boolean to check if the value has been set.
func (o *EmailMessage) GetSubjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subject, true
}

// SetSubject sets field value
func (o *EmailMessage) SetSubject(v string) {
	o.Subject = v
}

// GetFrom returns the From field value
func (o *EmailMessage) GetFrom() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *EmailMessage) GetFromOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *EmailMessage) SetFrom(v string) {
	o.From = v
}

// GetTo returns the To field value
func (o *EmailMessage) GetTo() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *EmailMessage) GetToOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.To, true
}

// SetTo sets field value
func (o *EmailMessage) SetTo(v []string) {
	o.To = v
}

// GetCc returns the Cc field value
func (o *EmailMessage) GetCc() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Cc
}

// GetCcOk returns a tuple with the Cc field value
// and a boolean to check if the value has been set.
func (o *EmailMessage) GetCcOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Cc, true
}

// SetCc sets field value
func (o *EmailMessage) SetCc(v []string) {
	o.Cc = v
}

// GetBcc returns the Bcc field value
func (o *EmailMessage) GetBcc() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Bcc
}

// GetBccOk returns a tuple with the Bcc field value
// and a boolean to check if the value has been set.
func (o *EmailMessage) GetBccOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Bcc, true
}

// SetBcc sets field value
func (o *EmailMessage) SetBcc(v []string) {
	o.Bcc = v
}

// GetText returns the Text field value
func (o *EmailMessage) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *EmailMessage) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *EmailMessage) SetText(v string) {
	o.Text = v
}

// GetHtml returns the Html field value
func (o *EmailMessage) GetHtml() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Html
}

// GetHtmlOk returns a tuple with the Html field value
// and a boolean to check if the value has been set.
func (o *EmailMessage) GetHtmlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Html, true
}

// SetHtml sets field value
func (o *EmailMessage) SetHtml(v string) {
	o.Html = v
}

// GetBodyText returns the BodyText field value
// If the value is explicit nil, the zero value for string will be returned
func (o *EmailMessage) GetBodyText() string {
	if o == nil || o.BodyText.Get() == nil {
		var ret string
		return ret
	}

	return *o.BodyText.Get()
}

// GetBodyTextOk returns a tuple with the BodyText field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailMessage) GetBodyTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BodyText.Get(), o.BodyText.IsSet()
}

// SetBodyText sets field value
func (o *EmailMessage) SetBodyText(v string) {
	o.BodyText.Set(&v)
}

// GetIsStarred returns the IsStarred field value
func (o *EmailMessage) GetIsStarred() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsStarred
}

// GetIsStarredOk returns a tuple with the IsStarred field value
// and a boolean to check if the value has been set.
func (o *EmailMessage) GetIsStarredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsStarred, true
}

// SetIsStarred sets field value
func (o *EmailMessage) SetIsStarred(v bool) {
	o.IsStarred = v
}

// GetIsRead returns the IsRead field value
func (o *EmailMessage) GetIsRead() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsRead
}

// GetIsReadOk returns a tuple with the IsRead field value
// and a boolean to check if the value has been set.
func (o *EmailMessage) GetIsReadOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsRead, true
}

// SetIsRead sets field value
func (o *EmailMessage) SetIsRead(v bool) {
	o.IsRead = v
}

// GetTags returns the Tags field value
func (o *EmailMessage) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *EmailMessage) GetTagsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *EmailMessage) SetTags(v []string) {
	o.Tags = v
}

// GetCategories returns the Categories field value
func (o *EmailMessage) GetCategories() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value
// and a boolean to check if the value has been set.
func (o *EmailMessage) GetCategoriesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Categories, true
}

// SetCategories sets field value
func (o *EmailMessage) SetCategories(v []string) {
	o.Categories = v
}

// GetExtractedOtp returns the ExtractedOtp field value
// If the value is explicit nil, the zero value for string will be returned
func (o *EmailMessage) GetExtractedOtp() string {
	if o == nil || o.ExtractedOtp.Get() == nil {
		var ret string
		return ret
	}

	return *o.ExtractedOtp.Get()
}

// GetExtractedOtpOk returns a tuple with the ExtractedOtp field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailMessage) GetExtractedOtpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExtractedOtp.Get(), o.ExtractedOtp.IsSet()
}

// SetExtractedOtp sets field value
func (o *EmailMessage) SetExtractedOtp(v string) {
	o.ExtractedOtp.Set(&v)
}

// GetCreatedAt returns the CreatedAt field value
func (o *EmailMessage) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *EmailMessage) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *EmailMessage) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetThreadCount returns the ThreadCount field value if set, zero value otherwise.
func (o *EmailMessage) GetThreadCount() int32 {
	if o == nil || IsNil(o.ThreadCount) {
		var ret int32
		return ret
	}
	return *o.ThreadCount
}

// GetThreadCountOk returns a tuple with the ThreadCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailMessage) GetThreadCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ThreadCount) {
		return nil, false
	}
	return o.ThreadCount, true
}

// HasThreadCount returns a boolean if a field has been set.
func (o *EmailMessage) HasThreadCount() bool {
	if o != nil && !IsNil(o.ThreadCount) {
		return true
	}

	return false
}

// SetThreadCount gets a reference to the given int32 and assigns it to the ThreadCount field.
func (o *EmailMessage) SetThreadCount(v int32) {
	o.ThreadCount = &v
}

func (o EmailMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["threadId"] = o.ThreadId
	toSerialize["parentMessageId"] = o.ParentMessageId.Get()
	toSerialize["subject"] = o.Subject
	toSerialize["from"] = o.From
	toSerialize["to"] = o.To
	toSerialize["cc"] = o.Cc
	toSerialize["bcc"] = o.Bcc
	toSerialize["text"] = o.Text
	toSerialize["html"] = o.Html
	toSerialize["bodyText"] = o.BodyText.Get()
	toSerialize["isStarred"] = o.IsStarred
	toSerialize["isRead"] = o.IsRead
	toSerialize["tags"] = o.Tags
	toSerialize["categories"] = o.Categories
	toSerialize["extractedOtp"] = o.ExtractedOtp.Get()
	toSerialize["createdAt"] = o.CreatedAt
	if !IsNil(o.ThreadCount) {
		toSerialize["threadCount"] = o.ThreadCount
	}
	return toSerialize, nil
}

func (o *EmailMessage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"threadId",
		"parentMessageId",
		"subject",
		"from",
		"to",
		"cc",
		"bcc",
		"text",
		"html",
		"bodyText",
		"isStarred",
		"isRead",
		"tags",
		"categories",
		"extractedOtp",
		"createdAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmailMessage := _EmailMessage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmailMessage)

	if err != nil {
		return err
	}

	*o = EmailMessage(varEmailMessage)

	return err
}

type NullableEmailMessage struct {
	value *EmailMessage
	isSet bool
}

func (v NullableEmailMessage) Get() *EmailMessage {
	return v.value
}

func (v *NullableEmailMessage) Set(val *EmailMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailMessage(val *EmailMessage) *NullableEmailMessage {
	return &NullableEmailMessage{value: val, isSet: true}
}

func (v NullableEmailMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


