/*
ProgrammableInbox Email Inboxes API

Email inbox management endpoints with API key support

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package programmableinbox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetEmailInboxOtp200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEmailInboxOtp200Response{}

// GetEmailInboxOtp200Response struct for GetEmailInboxOtp200Response
type GetEmailInboxOtp200Response struct {
	Data GetEmailInboxOtp200ResponseData `json:"data"`
}

type _GetEmailInboxOtp200Response GetEmailInboxOtp200Response

// NewGetEmailInboxOtp200Response instantiates a new GetEmailInboxOtp200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEmailInboxOtp200Response(data GetEmailInboxOtp200ResponseData) *GetEmailInboxOtp200Response {
	this := GetEmailInboxOtp200Response{}
	this.Data = data
	return &this
}

// NewGetEmailInboxOtp200ResponseWithDefaults instantiates a new GetEmailInboxOtp200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEmailInboxOtp200ResponseWithDefaults() *GetEmailInboxOtp200Response {
	this := GetEmailInboxOtp200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetEmailInboxOtp200Response) GetData() GetEmailInboxOtp200ResponseData {
	if o == nil {
		var ret GetEmailInboxOtp200ResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetEmailInboxOtp200Response) GetDataOk() (*GetEmailInboxOtp200ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetEmailInboxOtp200Response) SetData(v GetEmailInboxOtp200ResponseData) {
	o.Data = v
}

func (o GetEmailInboxOtp200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEmailInboxOtp200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GetEmailInboxOtp200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetEmailInboxOtp200Response := _GetEmailInboxOtp200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetEmailInboxOtp200Response)

	if err != nil {
		return err
	}

	*o = GetEmailInboxOtp200Response(varGetEmailInboxOtp200Response)

	return err
}

type NullableGetEmailInboxOtp200Response struct {
	value *GetEmailInboxOtp200Response
	isSet bool
}

func (v NullableGetEmailInboxOtp200Response) Get() *GetEmailInboxOtp200Response {
	return v.value
}

func (v *NullableGetEmailInboxOtp200Response) Set(val *GetEmailInboxOtp200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEmailInboxOtp200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEmailInboxOtp200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEmailInboxOtp200Response(val *GetEmailInboxOtp200Response) *NullableGetEmailInboxOtp200Response {
	return &NullableGetEmailInboxOtp200Response{value: val, isSet: true}
}

func (v NullableGetEmailInboxOtp200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEmailInboxOtp200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


