/*
ProgrammableInbox Email Inboxes API

Email inbox management endpoints with API key support

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package programmableinbox

import (
	"encoding/json"
)

// checks if the UpdateEmailInboxRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateEmailInboxRequest{}

// UpdateEmailInboxRequest struct for UpdateEmailInboxRequest
type UpdateEmailInboxRequest struct {
	// The new display label. Subject to the impersonation blocklist, so an inbox cannot be renamed into one.
	Name NullableString `json:"name,omitempty"`
}

// NewUpdateEmailInboxRequest instantiates a new UpdateEmailInboxRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateEmailInboxRequest() *UpdateEmailInboxRequest {
	this := UpdateEmailInboxRequest{}
	return &this
}

// NewUpdateEmailInboxRequestWithDefaults instantiates a new UpdateEmailInboxRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateEmailInboxRequestWithDefaults() *UpdateEmailInboxRequest {
	this := UpdateEmailInboxRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateEmailInboxRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateEmailInboxRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *UpdateEmailInboxRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *UpdateEmailInboxRequest) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *UpdateEmailInboxRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *UpdateEmailInboxRequest) UnsetName() {
	o.Name.Unset()
}

func (o UpdateEmailInboxRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateEmailInboxRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	return toSerialize, nil
}

type NullableUpdateEmailInboxRequest struct {
	value *UpdateEmailInboxRequest
	isSet bool
}

func (v NullableUpdateEmailInboxRequest) Get() *UpdateEmailInboxRequest {
	return v.value
}

func (v *NullableUpdateEmailInboxRequest) Set(val *UpdateEmailInboxRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateEmailInboxRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateEmailInboxRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateEmailInboxRequest(val *UpdateEmailInboxRequest) *NullableUpdateEmailInboxRequest {
	return &NullableUpdateEmailInboxRequest{value: val, isSet: true}
}

func (v NullableUpdateEmailInboxRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateEmailInboxRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


