/*
ProgrammableInbox Email Inboxes API

Email inbox management endpoints with API key support

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package programmableinbox

import (
	"encoding/json"
)

// checks if the GetEmailInbox200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEmailInbox200Response{}

// GetEmailInbox200Response struct for GetEmailInbox200Response
type GetEmailInbox200Response struct {
	Data *EmailInbox `json:"data,omitempty"`
}

// NewGetEmailInbox200Response instantiates a new GetEmailInbox200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEmailInbox200Response() *GetEmailInbox200Response {
	this := GetEmailInbox200Response{}
	return &this
}

// NewGetEmailInbox200ResponseWithDefaults instantiates a new GetEmailInbox200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEmailInbox200ResponseWithDefaults() *GetEmailInbox200Response {
	this := GetEmailInbox200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetEmailInbox200Response) GetData() EmailInbox {
	if o == nil || IsNil(o.Data) {
		var ret EmailInbox
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEmailInbox200Response) GetDataOk() (*EmailInbox, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetEmailInbox200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given EmailInbox and assigns it to the Data field.
func (o *GetEmailInbox200Response) SetData(v EmailInbox) {
	o.Data = &v
}

func (o GetEmailInbox200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEmailInbox200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableGetEmailInbox200Response struct {
	value *GetEmailInbox200Response
	isSet bool
}

func (v NullableGetEmailInbox200Response) Get() *GetEmailInbox200Response {
	return v.value
}

func (v *NullableGetEmailInbox200Response) Set(val *GetEmailInbox200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEmailInbox200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEmailInbox200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEmailInbox200Response(val *GetEmailInbox200Response) *NullableGetEmailInbox200Response {
	return &NullableGetEmailInbox200Response{value: val, isSet: true}
}

func (v NullableGetEmailInbox200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEmailInbox200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


