/*
ProgrammableInbox Email Inboxes API

Email inbox management endpoints with API key support

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package programmableinbox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetEmailInboxMessages200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEmailInboxMessages200Response{}

// GetEmailInboxMessages200Response struct for GetEmailInboxMessages200Response
type GetEmailInboxMessages200Response struct {
	Data GetEmailInboxMessages200ResponseData `json:"data"`
}

type _GetEmailInboxMessages200Response GetEmailInboxMessages200Response

// NewGetEmailInboxMessages200Response instantiates a new GetEmailInboxMessages200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEmailInboxMessages200Response(data GetEmailInboxMessages200ResponseData) *GetEmailInboxMessages200Response {
	this := GetEmailInboxMessages200Response{}
	this.Data = data
	return &this
}

// NewGetEmailInboxMessages200ResponseWithDefaults instantiates a new GetEmailInboxMessages200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEmailInboxMessages200ResponseWithDefaults() *GetEmailInboxMessages200Response {
	this := GetEmailInboxMessages200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetEmailInboxMessages200Response) GetData() GetEmailInboxMessages200ResponseData {
	if o == nil {
		var ret GetEmailInboxMessages200ResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetEmailInboxMessages200Response) GetDataOk() (*GetEmailInboxMessages200ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetEmailInboxMessages200Response) SetData(v GetEmailInboxMessages200ResponseData) {
	o.Data = v
}

func (o GetEmailInboxMessages200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEmailInboxMessages200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GetEmailInboxMessages200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetEmailInboxMessages200Response := _GetEmailInboxMessages200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetEmailInboxMessages200Response)

	if err != nil {
		return err
	}

	*o = GetEmailInboxMessages200Response(varGetEmailInboxMessages200Response)

	return err
}

type NullableGetEmailInboxMessages200Response struct {
	value *GetEmailInboxMessages200Response
	isSet bool
}

func (v NullableGetEmailInboxMessages200Response) Get() *GetEmailInboxMessages200Response {
	return v.value
}

func (v *NullableGetEmailInboxMessages200Response) Set(val *GetEmailInboxMessages200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEmailInboxMessages200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEmailInboxMessages200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEmailInboxMessages200Response(val *GetEmailInboxMessages200Response) *NullableGetEmailInboxMessages200Response {
	return &NullableGetEmailInboxMessages200Response{value: val, isSet: true}
}

func (v NullableGetEmailInboxMessages200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEmailInboxMessages200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


