/*
ProgrammableInbox Email Inboxes API

Email inbox management endpoints with API key support

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package programmableinbox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetEmailMessage200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEmailMessage200Response{}

// GetEmailMessage200Response struct for GetEmailMessage200Response
type GetEmailMessage200Response struct {
	Data EmailMessage `json:"data"`
}

type _GetEmailMessage200Response GetEmailMessage200Response

// NewGetEmailMessage200Response instantiates a new GetEmailMessage200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEmailMessage200Response(data EmailMessage) *GetEmailMessage200Response {
	this := GetEmailMessage200Response{}
	this.Data = data
	return &this
}

// NewGetEmailMessage200ResponseWithDefaults instantiates a new GetEmailMessage200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEmailMessage200ResponseWithDefaults() *GetEmailMessage200Response {
	this := GetEmailMessage200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetEmailMessage200Response) GetData() EmailMessage {
	if o == nil {
		var ret EmailMessage
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetEmailMessage200Response) GetDataOk() (*EmailMessage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetEmailMessage200Response) SetData(v EmailMessage) {
	o.Data = v
}

func (o GetEmailMessage200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEmailMessage200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GetEmailMessage200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetEmailMessage200Response := _GetEmailMessage200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetEmailMessage200Response)

	if err != nil {
		return err
	}

	*o = GetEmailMessage200Response(varGetEmailMessage200Response)

	return err
}

type NullableGetEmailMessage200Response struct {
	value *GetEmailMessage200Response
	isSet bool
}

func (v NullableGetEmailMessage200Response) Get() *GetEmailMessage200Response {
	return v.value
}

func (v *NullableGetEmailMessage200Response) Set(val *GetEmailMessage200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEmailMessage200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEmailMessage200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEmailMessage200Response(val *GetEmailMessage200Response) *NullableGetEmailMessage200Response {
	return &NullableGetEmailMessage200Response{value: val, isSet: true}
}

func (v NullableGetEmailMessage200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEmailMessage200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


