/*
ProgrammableInbox Email Inboxes API

Email inbox management endpoints with API key support

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package programmableinbox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetEmailInboxMessages200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEmailInboxMessages200ResponseData{}

// GetEmailInboxMessages200ResponseData struct for GetEmailInboxMessages200ResponseData
type GetEmailInboxMessages200ResponseData struct {
	Messages []GetEmailInboxMessages200ResponseDataMessagesInner `json:"messages"`
	// Cursor for the next page, or null if there are no more results
	NextCursor NullableString `json:"nextCursor"`
	// True if more results exist beyond this page
	HasMore bool `json:"hasMore"`
}

type _GetEmailInboxMessages200ResponseData GetEmailInboxMessages200ResponseData

// NewGetEmailInboxMessages200ResponseData instantiates a new GetEmailInboxMessages200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEmailInboxMessages200ResponseData(messages []GetEmailInboxMessages200ResponseDataMessagesInner, nextCursor NullableString, hasMore bool) *GetEmailInboxMessages200ResponseData {
	this := GetEmailInboxMessages200ResponseData{}
	this.Messages = messages
	this.NextCursor = nextCursor
	this.HasMore = hasMore
	return &this
}

// NewGetEmailInboxMessages200ResponseDataWithDefaults instantiates a new GetEmailInboxMessages200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEmailInboxMessages200ResponseDataWithDefaults() *GetEmailInboxMessages200ResponseData {
	this := GetEmailInboxMessages200ResponseData{}
	return &this
}

// GetMessages returns the Messages field value
func (o *GetEmailInboxMessages200ResponseData) GetMessages() []GetEmailInboxMessages200ResponseDataMessagesInner {
	if o == nil {
		var ret []GetEmailInboxMessages200ResponseDataMessagesInner
		return ret
	}

	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value
// and a boolean to check if the value has been set.
func (o *GetEmailInboxMessages200ResponseData) GetMessagesOk() ([]GetEmailInboxMessages200ResponseDataMessagesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Messages, true
}

// SetMessages sets field value
func (o *GetEmailInboxMessages200ResponseData) SetMessages(v []GetEmailInboxMessages200ResponseDataMessagesInner) {
	o.Messages = v
}

// GetNextCursor returns the NextCursor field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetEmailInboxMessages200ResponseData) GetNextCursor() string {
	if o == nil || o.NextCursor.Get() == nil {
		var ret string
		return ret
	}

	return *o.NextCursor.Get()
}

// GetNextCursorOk returns a tuple with the NextCursor field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetEmailInboxMessages200ResponseData) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextCursor.Get(), o.NextCursor.IsSet()
}

// SetNextCursor sets field value
func (o *GetEmailInboxMessages200ResponseData) SetNextCursor(v string) {
	o.NextCursor.Set(&v)
}

// GetHasMore returns the HasMore field value
func (o *GetEmailInboxMessages200ResponseData) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *GetEmailInboxMessages200ResponseData) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *GetEmailInboxMessages200ResponseData) SetHasMore(v bool) {
	o.HasMore = v
}

func (o GetEmailInboxMessages200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEmailInboxMessages200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["messages"] = o.Messages
	toSerialize["nextCursor"] = o.NextCursor.Get()
	toSerialize["hasMore"] = o.HasMore
	return toSerialize, nil
}

func (o *GetEmailInboxMessages200ResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"messages",
		"nextCursor",
		"hasMore",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetEmailInboxMessages200ResponseData := _GetEmailInboxMessages200ResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetEmailInboxMessages200ResponseData)

	if err != nil {
		return err
	}

	*o = GetEmailInboxMessages200ResponseData(varGetEmailInboxMessages200ResponseData)

	return err
}

type NullableGetEmailInboxMessages200ResponseData struct {
	value *GetEmailInboxMessages200ResponseData
	isSet bool
}

func (v NullableGetEmailInboxMessages200ResponseData) Get() *GetEmailInboxMessages200ResponseData {
	return v.value
}

func (v *NullableGetEmailInboxMessages200ResponseData) Set(val *GetEmailInboxMessages200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEmailInboxMessages200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEmailInboxMessages200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEmailInboxMessages200ResponseData(val *GetEmailInboxMessages200ResponseData) *NullableGetEmailInboxMessages200ResponseData {
	return &NullableGetEmailInboxMessages200ResponseData{value: val, isSet: true}
}

func (v NullableGetEmailInboxMessages200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEmailInboxMessages200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


