/* tslint:disable */
/* eslint-disable */
/**
 * ProgrammableInbox Email Inboxes API
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailInbox } from './EmailInbox';
import {
    EmailInboxFromJSON,
    EmailInboxFromJSONTyped,
    EmailInboxToJSON,
    EmailInboxToJSONTyped,
} from './EmailInbox';

/**
 * 
 * @export
 * @interface CreateEmailInbox201Response
 */
export interface CreateEmailInbox201Response {
    /**
     * 
     * @type {EmailInbox}
     * @memberof CreateEmailInbox201Response
     */
    data: EmailInbox;
}

/**
 * Check if a given object implements the CreateEmailInbox201Response interface.
 */
export function instanceOfCreateEmailInbox201Response(value: object): value is CreateEmailInbox201Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CreateEmailInbox201ResponseFromJSON(json: any): CreateEmailInbox201Response {
    return CreateEmailInbox201ResponseFromJSONTyped(json, false);
}

export function CreateEmailInbox201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEmailInbox201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': EmailInboxFromJSON(json['data']),
    };
}

export function CreateEmailInbox201ResponseToJSON(json: any): CreateEmailInbox201Response {
    return CreateEmailInbox201ResponseToJSONTyped(json, false);
}

export function CreateEmailInbox201ResponseToJSONTyped(value?: CreateEmailInbox201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': EmailInboxToJSON(value['data']),
    };
}

