/* tslint:disable */
/* eslint-disable */
/**
 * ProgrammableInbox Email Inboxes API
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetEmailInboxMessages200ResponseDataMessagesInner } from './GetEmailInboxMessages200ResponseDataMessagesInner';
import {
    GetEmailInboxMessages200ResponseDataMessagesInnerFromJSON,
    GetEmailInboxMessages200ResponseDataMessagesInnerFromJSONTyped,
    GetEmailInboxMessages200ResponseDataMessagesInnerToJSON,
    GetEmailInboxMessages200ResponseDataMessagesInnerToJSONTyped,
} from './GetEmailInboxMessages200ResponseDataMessagesInner';

/**
 * 
 * @export
 * @interface GetEmailInboxMessages200ResponseData
 */
export interface GetEmailInboxMessages200ResponseData {
    /**
     * 
     * @type {Array<GetEmailInboxMessages200ResponseDataMessagesInner>}
     * @memberof GetEmailInboxMessages200ResponseData
     */
    messages: Array<GetEmailInboxMessages200ResponseDataMessagesInner>;
    /**
     * Cursor for the next page, or null if there are no more results
     * @type {string}
     * @memberof GetEmailInboxMessages200ResponseData
     */
    nextCursor: string | null;
    /**
     * True if more results exist beyond this page
     * @type {boolean}
     * @memberof GetEmailInboxMessages200ResponseData
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the GetEmailInboxMessages200ResponseData interface.
 */
export function instanceOfGetEmailInboxMessages200ResponseData(value: object): value is GetEmailInboxMessages200ResponseData {
    if (!('messages' in value) || value['messages'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function GetEmailInboxMessages200ResponseDataFromJSON(json: any): GetEmailInboxMessages200ResponseData {
    return GetEmailInboxMessages200ResponseDataFromJSONTyped(json, false);
}

export function GetEmailInboxMessages200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEmailInboxMessages200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'messages': ((json['messages'] as Array<any>).map(GetEmailInboxMessages200ResponseDataMessagesInnerFromJSON)),
        'nextCursor': json['nextCursor'],
        'hasMore': json['hasMore'],
    };
}

export function GetEmailInboxMessages200ResponseDataToJSON(json: any): GetEmailInboxMessages200ResponseData {
    return GetEmailInboxMessages200ResponseDataToJSONTyped(json, false);
}

export function GetEmailInboxMessages200ResponseDataToJSONTyped(value?: GetEmailInboxMessages200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messages': ((value['messages'] as Array<any>).map(GetEmailInboxMessages200ResponseDataMessagesInnerToJSON)),
        'nextCursor': value['nextCursor'],
        'hasMore': value['hasMore'],
    };
}

