/* tslint:disable */
/* eslint-disable */
/**
 * ProgrammableInbox Email Inboxes API
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailMessage } from './EmailMessage';
import {
    EmailMessageFromJSON,
    EmailMessageFromJSONTyped,
    EmailMessageToJSON,
    EmailMessageToJSONTyped,
} from './EmailMessage';

/**
 * 
 * @export
 * @interface GetEmailInboxOtp200ResponseData
 */
export interface GetEmailInboxOtp200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof GetEmailInboxOtp200ResponseData
     */
    otp: string;
    /**
     * 
     * @type {EmailMessage}
     * @memberof GetEmailInboxOtp200ResponseData
     */
    message: EmailMessage;
}

/**
 * Check if a given object implements the GetEmailInboxOtp200ResponseData interface.
 */
export function instanceOfGetEmailInboxOtp200ResponseData(value: object): value is GetEmailInboxOtp200ResponseData {
    if (!('otp' in value) || value['otp'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function GetEmailInboxOtp200ResponseDataFromJSON(json: any): GetEmailInboxOtp200ResponseData {
    return GetEmailInboxOtp200ResponseDataFromJSONTyped(json, false);
}

export function GetEmailInboxOtp200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEmailInboxOtp200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'otp': json['otp'],
        'message': EmailMessageFromJSON(json['message']),
    };
}

export function GetEmailInboxOtp200ResponseDataToJSON(json: any): GetEmailInboxOtp200ResponseData {
    return GetEmailInboxOtp200ResponseDataToJSONTyped(json, false);
}

export function GetEmailInboxOtp200ResponseDataToJSONTyped(value?: GetEmailInboxOtp200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'otp': value['otp'],
        'message': EmailMessageToJSON(value['message']),
    };
}

