/* tslint:disable */
/* eslint-disable */
/**
 * ProgrammableInbox Email Inboxes API
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetEmailInboxOtp200ResponseData } from './GetEmailInboxOtp200ResponseData';
import {
    GetEmailInboxOtp200ResponseDataFromJSON,
    GetEmailInboxOtp200ResponseDataFromJSONTyped,
    GetEmailInboxOtp200ResponseDataToJSON,
    GetEmailInboxOtp200ResponseDataToJSONTyped,
} from './GetEmailInboxOtp200ResponseData';

/**
 * 
 * @export
 * @interface GetEmailInboxOtp200Response
 */
export interface GetEmailInboxOtp200Response {
    /**
     * 
     * @type {GetEmailInboxOtp200ResponseData}
     * @memberof GetEmailInboxOtp200Response
     */
    data: GetEmailInboxOtp200ResponseData;
}

/**
 * Check if a given object implements the GetEmailInboxOtp200Response interface.
 */
export function instanceOfGetEmailInboxOtp200Response(value: object): value is GetEmailInboxOtp200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetEmailInboxOtp200ResponseFromJSON(json: any): GetEmailInboxOtp200Response {
    return GetEmailInboxOtp200ResponseFromJSONTyped(json, false);
}

export function GetEmailInboxOtp200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEmailInboxOtp200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': GetEmailInboxOtp200ResponseDataFromJSON(json['data']),
    };
}

export function GetEmailInboxOtp200ResponseToJSON(json: any): GetEmailInboxOtp200Response {
    return GetEmailInboxOtp200ResponseToJSONTyped(json, false);
}

export function GetEmailInboxOtp200ResponseToJSONTyped(value?: GetEmailInboxOtp200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': GetEmailInboxOtp200ResponseDataToJSON(value['data']),
    };
}

