/* tslint:disable */
/* eslint-disable */
/**
 * ProgrammableInbox Email Inboxes API
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetEmailInboxMessages200ResponseData } from './GetEmailInboxMessages200ResponseData';
import {
    GetEmailInboxMessages200ResponseDataFromJSON,
    GetEmailInboxMessages200ResponseDataFromJSONTyped,
    GetEmailInboxMessages200ResponseDataToJSON,
    GetEmailInboxMessages200ResponseDataToJSONTyped,
} from './GetEmailInboxMessages200ResponseData';

/**
 * 
 * @export
 * @interface GetEmailInboxMessages200Response
 */
export interface GetEmailInboxMessages200Response {
    /**
     * 
     * @type {GetEmailInboxMessages200ResponseData}
     * @memberof GetEmailInboxMessages200Response
     */
    data: GetEmailInboxMessages200ResponseData;
}

/**
 * Check if a given object implements the GetEmailInboxMessages200Response interface.
 */
export function instanceOfGetEmailInboxMessages200Response(value: object): value is GetEmailInboxMessages200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetEmailInboxMessages200ResponseFromJSON(json: any): GetEmailInboxMessages200Response {
    return GetEmailInboxMessages200ResponseFromJSONTyped(json, false);
}

export function GetEmailInboxMessages200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEmailInboxMessages200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': GetEmailInboxMessages200ResponseDataFromJSON(json['data']),
    };
}

export function GetEmailInboxMessages200ResponseToJSON(json: any): GetEmailInboxMessages200Response {
    return GetEmailInboxMessages200ResponseToJSONTyped(json, false);
}

export function GetEmailInboxMessages200ResponseToJSONTyped(value?: GetEmailInboxMessages200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': GetEmailInboxMessages200ResponseDataToJSON(value['data']),
    };
}

