/* tslint:disable */
/* eslint-disable */
/**
 * ProgrammableInbox Email Inboxes API
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetEmailInboxOtp200ResponseData
 */
export interface GetEmailInboxOtp200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof GetEmailInboxOtp200ResponseData
     */
    otp: string;
    /**
     * 
     * @type {Date}
     * @memberof GetEmailInboxOtp200ResponseData
     */
    receivedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof GetEmailInboxOtp200ResponseData
     */
    messageId: string;
    /**
     * 
     * @type {string}
     * @memberof GetEmailInboxOtp200ResponseData
     */
    from: string;
}

/**
 * Check if a given object implements the GetEmailInboxOtp200ResponseData interface.
 */
export function instanceOfGetEmailInboxOtp200ResponseData(value: object): value is GetEmailInboxOtp200ResponseData {
    if (!('otp' in value) || value['otp'] === undefined) return false;
    if (!('receivedAt' in value) || value['receivedAt'] === undefined) return false;
    if (!('messageId' in value) || value['messageId'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    return true;
}

export function GetEmailInboxOtp200ResponseDataFromJSON(json: any): GetEmailInboxOtp200ResponseData {
    return GetEmailInboxOtp200ResponseDataFromJSONTyped(json, false);
}

export function GetEmailInboxOtp200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEmailInboxOtp200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'otp': json['otp'],
        'receivedAt': (new Date(json['receivedAt'])),
        'messageId': json['messageId'],
        'from': json['from'],
    };
}

export function GetEmailInboxOtp200ResponseDataToJSON(json: any): GetEmailInboxOtp200ResponseData {
    return GetEmailInboxOtp200ResponseDataToJSONTyped(json, false);
}

export function GetEmailInboxOtp200ResponseDataToJSONTyped(value?: GetEmailInboxOtp200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'otp': value['otp'],
        'receivedAt': value['receivedAt'].toISOString(),
        'messageId': value['messageId'],
        'from': value['from'],
    };
}

