/* tslint:disable */
/* eslint-disable */
/**
 * ProgrammableInbox Email Inboxes API
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailMessage } from './EmailMessage';
import {
    EmailMessageFromJSON,
    EmailMessageFromJSONTyped,
    EmailMessageToJSON,
    EmailMessageToJSONTyped,
} from './EmailMessage';

/**
 * 
 * @export
 * @interface GetEmailMessage200Response
 */
export interface GetEmailMessage200Response {
    /**
     * 
     * @type {EmailMessage}
     * @memberof GetEmailMessage200Response
     */
    data: EmailMessage;
}

/**
 * Check if a given object implements the GetEmailMessage200Response interface.
 */
export function instanceOfGetEmailMessage200Response(value: object): value is GetEmailMessage200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetEmailMessage200ResponseFromJSON(json: any): GetEmailMessage200Response {
    return GetEmailMessage200ResponseFromJSONTyped(json, false);
}

export function GetEmailMessage200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEmailMessage200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': EmailMessageFromJSON(json['data']),
    };
}

export function GetEmailMessage200ResponseToJSON(json: any): GetEmailMessage200Response {
    return GetEmailMessage200ResponseToJSONTyped(json, false);
}

export function GetEmailMessage200ResponseToJSONTyped(value?: GetEmailMessage200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': EmailMessageToJSON(value['data']),
    };
}

