/* tslint:disable */
/* eslint-disable */
/**
 * ProgrammableInbox Email Inboxes API
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailInbox } from './EmailInbox';
import {
    EmailInboxFromJSON,
    EmailInboxFromJSONTyped,
    EmailInboxToJSON,
    EmailInboxToJSONTyped,
} from './EmailInbox';

/**
 * 
 * @export
 * @interface ListEmailInboxes200Response
 */
export interface ListEmailInboxes200Response {
    /**
     * 
     * @type {Array<EmailInbox>}
     * @memberof ListEmailInboxes200Response
     */
    data: Array<EmailInbox>;
}

/**
 * Check if a given object implements the ListEmailInboxes200Response interface.
 */
export function instanceOfListEmailInboxes200Response(value: object): value is ListEmailInboxes200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListEmailInboxes200ResponseFromJSON(json: any): ListEmailInboxes200Response {
    return ListEmailInboxes200ResponseFromJSONTyped(json, false);
}

export function ListEmailInboxes200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListEmailInboxes200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(EmailInboxFromJSON)),
    };
}

export function ListEmailInboxes200ResponseToJSON(json: any): ListEmailInboxes200Response {
    return ListEmailInboxes200ResponseToJSONTyped(json, false);
}

export function ListEmailInboxes200ResponseToJSONTyped(value?: ListEmailInboxes200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(EmailInboxToJSON)),
    };
}

