/* tslint:disable */
/* eslint-disable */
/**
 * ProgrammableInbox Email Inboxes API
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateEmailInboxRequest
 */
export interface UpdateEmailInboxRequest {
    /**
     * The new display label. Subject to the impersonation blocklist, so an inbox cannot be renamed into one.
     * @type {string}
     * @memberof UpdateEmailInboxRequest
     */
    name?: string | null;
    /**
     * Accepted only when it matches the current address. Present so a client can round-trip a full record; any other value is a 409.
     * @type {string}
     * @memberof UpdateEmailInboxRequest
     */
    email?: string;
}

/**
 * Check if a given object implements the UpdateEmailInboxRequest interface.
 */
export function instanceOfUpdateEmailInboxRequest(value: object): value is UpdateEmailInboxRequest {
    return true;
}

export function UpdateEmailInboxRequestFromJSON(json: any): UpdateEmailInboxRequest {
    return UpdateEmailInboxRequestFromJSONTyped(json, false);
}

export function UpdateEmailInboxRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEmailInboxRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] === undefined ? undefined : json['name'] === null ? null : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function UpdateEmailInboxRequestToJSON(json: any): UpdateEmailInboxRequest {
    return UpdateEmailInboxRequestToJSONTyped(json, false);
}

export function UpdateEmailInboxRequestToJSONTyped(value?: UpdateEmailInboxRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
    };
}

