# coding: utf-8

"""
    ProgrammableInbox Email Inboxes API

    Email inbox management endpoints with API key support

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EmailMessage(BaseModel):
    """
    An email message
    """ # noqa: E501
    id: StrictStr = Field(json_schema_extra={"examples": ["msg-1"]})
    thread_id: StrictStr = Field(alias="threadId", json_schema_extra={"examples": ["thread-1"]})
    parent_message_id: Optional[StrictStr] = Field(alias="parentMessageId", json_schema_extra={"examples": ["msg-0"]})
    subject: StrictStr = Field(json_schema_extra={"examples": ["Support Request"]})
    var_from: StrictStr = Field(alias="from", json_schema_extra={"examples": ["customer@example.com"]})
    to: List[StrictStr]
    cc: List[StrictStr]
    bcc: List[StrictStr]
    text: StrictStr = Field(json_schema_extra={"examples": ["Hello, I need help with..."]})
    html: StrictStr = Field(json_schema_extra={"examples": ["<p>Hello, I need help with...</p>"]})
    body_text: Optional[StrictStr] = Field(description="Plain text of the body, and the field the `q` parameter searches. Equal to `text` when the sender supplied a text part, otherwise extracted from `html`. Null for messages stored before this field existed.", alias="bodyText", json_schema_extra={"examples": ["Hello, I need help with..."]})
    is_starred: StrictBool = Field(alias="isStarred", json_schema_extra={"examples": [False]})
    is_read: StrictBool = Field(description="Inbox-wide, not per-user: one shared flag reflecting whether any viewer has opened this message.", alias="isRead", json_schema_extra={"examples": [False]})
    tags: List[StrictStr]
    categories: List[StrictStr] = Field(description="Categories assigned to the message. Matched by the `categories` parameter.")
    extracted_otp: Optional[StrictStr] = Field(description="One-time code parsed from the message body. Derived from text/html, which the same email_messages:read scope already returns.", alias="extractedOtp", json_schema_extra={"examples": ["123456"]})
    created_at: datetime = Field(alias="createdAt")
    thread_count: Optional[StrictInt] = Field(default=None, description="Number of messages in the thread (present only in grouped mode)", alias="threadCount")
    __properties: ClassVar[List[str]] = ["id", "threadId", "parentMessageId", "subject", "from", "to", "cc", "bcc", "text", "html", "bodyText", "isStarred", "isRead", "tags", "categories", "extractedOtp", "createdAt", "threadCount"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EmailMessage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if parent_message_id (nullable) is None
        # and model_fields_set contains the field
        if self.parent_message_id is None and "parent_message_id" in self.model_fields_set:
            _dict['parentMessageId'] = None

        # set to None if body_text (nullable) is None
        # and model_fields_set contains the field
        if self.body_text is None and "body_text" in self.model_fields_set:
            _dict['bodyText'] = None

        # set to None if extracted_otp (nullable) is None
        # and model_fields_set contains the field
        if self.extracted_otp is None and "extracted_otp" in self.model_fields_set:
            _dict['extractedOtp'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EmailMessage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "threadId": obj.get("threadId"),
            "parentMessageId": obj.get("parentMessageId"),
            "subject": obj.get("subject"),
            "from": obj.get("from"),
            "to": obj.get("to"),
            "cc": obj.get("cc"),
            "bcc": obj.get("bcc"),
            "text": obj.get("text"),
            "html": obj.get("html"),
            "bodyText": obj.get("bodyText"),
            "isStarred": obj.get("isStarred"),
            "isRead": obj.get("isRead"),
            "tags": obj.get("tags"),
            "categories": obj.get("categories"),
            "extractedOtp": obj.get("extractedOtp"),
            "createdAt": obj.get("createdAt"),
            "threadCount": obj.get("threadCount")
        })
        return _obj


