# coding: utf-8

"""
    ProgrammableInbox Email Inboxes API

    Email inbox management endpoints with API key support

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from programmableinbox.models.get_email_inbox_messages200_response_data_messages_inner import GetEmailInboxMessages200ResponseDataMessagesInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetEmailInboxMessages200ResponseData(BaseModel):
    """
    GetEmailInboxMessages200ResponseData
    """ # noqa: E501
    messages: List[GetEmailInboxMessages200ResponseDataMessagesInner]
    next_cursor: Optional[StrictStr] = Field(description="Cursor for the next page, or null if there are no more results", alias="nextCursor")
    has_more: StrictBool = Field(description="True if more results exist beyond this page", alias="hasMore")
    __properties: ClassVar[List[str]] = ["messages", "nextCursor", "hasMore"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetEmailInboxMessages200ResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in messages (list)
        _items = []
        if self.messages:
            for _item_messages in self.messages:
                if _item_messages:
                    _items.append(_item_messages.to_dict())
            _dict['messages'] = _items
        # set to None if next_cursor (nullable) is None
        # and model_fields_set contains the field
        if self.next_cursor is None and "next_cursor" in self.model_fields_set:
            _dict['nextCursor'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetEmailInboxMessages200ResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "messages": [GetEmailInboxMessages200ResponseDataMessagesInner.from_dict(_item) for _item in obj["messages"]] if obj.get("messages") is not None else None,
            "nextCursor": obj.get("nextCursor"),
            "hasMore": obj.get("hasMore")
        })
        return _obj


