/*
 * ProgrammableInbox Email Inboxes API
 *
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProgrammableInbox.Sdk.Model;
using ProgrammableInbox.Sdk.Client;
using System.Reflection;

namespace ProgrammableInbox.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing CreateEmailInboxRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateEmailInboxRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateEmailInboxRequest
        //private CreateEmailInboxRequest instance;

        public CreateEmailInboxRequestTests()
        {
            // TODO uncomment below to create an instance of CreateEmailInboxRequest
            //instance = new CreateEmailInboxRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateEmailInboxRequest
        /// </summary>
        [Fact]
        public void CreateEmailInboxRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateEmailInboxRequest
            //Assert.IsType<CreateEmailInboxRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'OrganizationId'
        /// </summary>
        [Fact]
        public void OrganizationIdTest()
        {
            // TODO unit test for the property 'OrganizationId'
        }
    }
}
