/*
 * ProgrammableInbox Email Inboxes API
 *
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProgrammableInbox.Sdk.Model;
using ProgrammableInbox.Sdk.Client;
using System.Reflection;

namespace ProgrammableInbox.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing CreateEmailInbox201Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateEmailInbox201ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateEmailInbox201Response
        //private CreateEmailInbox201Response instance;

        public CreateEmailInbox201ResponseTests()
        {
            // TODO uncomment below to create an instance of CreateEmailInbox201Response
            //instance = new CreateEmailInbox201Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateEmailInbox201Response
        /// </summary>
        [Fact]
        public void CreateEmailInbox201ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateEmailInbox201Response
            //Assert.IsType<CreateEmailInbox201Response>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
