/*
 * ProgrammableInbox Email Inboxes API
 *
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProgrammableInbox.Sdk.Model;
using ProgrammableInbox.Sdk.Client;
using System.Reflection;

namespace ProgrammableInbox.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing EmailMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmailMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmailMessage
        //private EmailMessage instance;

        public EmailMessageTests()
        {
            // TODO uncomment below to create an instance of EmailMessage
            //instance = new EmailMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmailMessage
        /// </summary>
        [Fact]
        public void EmailMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmailMessage
            //Assert.IsType<EmailMessage>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'ThreadId'
        /// </summary>
        [Fact]
        public void ThreadIdTest()
        {
            // TODO unit test for the property 'ThreadId'
        }

        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }

        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }

        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }

        /// <summary>
        /// Test the property 'Cc'
        /// </summary>
        [Fact]
        public void CcTest()
        {
            // TODO unit test for the property 'Cc'
        }

        /// <summary>
        /// Test the property 'Bcc'
        /// </summary>
        [Fact]
        public void BccTest()
        {
            // TODO unit test for the property 'Bcc'
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }

        /// <summary>
        /// Test the property 'Html'
        /// </summary>
        [Fact]
        public void HtmlTest()
        {
            // TODO unit test for the property 'Html'
        }

        /// <summary>
        /// Test the property 'IsStarred'
        /// </summary>
        [Fact]
        public void IsStarredTest()
        {
            // TODO unit test for the property 'IsStarred'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }

        /// <summary>
        /// Test the property 'Categories'
        /// </summary>
        [Fact]
        public void CategoriesTest()
        {
            // TODO unit test for the property 'Categories'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'ParentMessageId'
        /// </summary>
        [Fact]
        public void ParentMessageIdTest()
        {
            // TODO unit test for the property 'ParentMessageId'
        }

        /// <summary>
        /// Test the property 'BodyText'
        /// </summary>
        [Fact]
        public void BodyTextTest()
        {
            // TODO unit test for the property 'BodyText'
        }

        /// <summary>
        /// Test the property 'ExtractedOtp'
        /// </summary>
        [Fact]
        public void ExtractedOtpTest()
        {
            // TODO unit test for the property 'ExtractedOtp'
        }

        /// <summary>
        /// Test the property 'ThreadCount'
        /// </summary>
        [Fact]
        public void ThreadCountTest()
        {
            // TODO unit test for the property 'ThreadCount'
        }
    }
}
