/*
 * ProgrammableInbox Email Inboxes API
 *
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProgrammableInbox.Sdk.Model;
using ProgrammableInbox.Sdk.Client;
using System.Reflection;

namespace ProgrammableInbox.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing GetEmailInboxMessages200ResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetEmailInboxMessages200ResponseDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetEmailInboxMessages200ResponseData
        //private GetEmailInboxMessages200ResponseData instance;

        public GetEmailInboxMessages200ResponseDataTests()
        {
            // TODO uncomment below to create an instance of GetEmailInboxMessages200ResponseData
            //instance = new GetEmailInboxMessages200ResponseData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetEmailInboxMessages200ResponseData
        /// </summary>
        [Fact]
        public void GetEmailInboxMessages200ResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetEmailInboxMessages200ResponseData
            //Assert.IsType<GetEmailInboxMessages200ResponseData>(instance);
        }

        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Fact]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }

        /// <summary>
        /// Test the property 'HasMore'
        /// </summary>
        [Fact]
        public void HasMoreTest()
        {
            // TODO unit test for the property 'HasMore'
        }

        /// <summary>
        /// Test the property 'NextCursor'
        /// </summary>
        [Fact]
        public void NextCursorTest()
        {
            // TODO unit test for the property 'NextCursor'
        }
    }
}
