/*
 * ProgrammableInbox Email Inboxes API
 *
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ProgrammableInbox.Sdk.Model;
using ProgrammableInbox.Sdk.Client;
using System.Reflection;

namespace ProgrammableInbox.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing GetEmailInboxOtp200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetEmailInboxOtp200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetEmailInboxOtp200Response
        //private GetEmailInboxOtp200Response instance;

        public GetEmailInboxOtp200ResponseTests()
        {
            // TODO uncomment below to create an instance of GetEmailInboxOtp200Response
            //instance = new GetEmailInboxOtp200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetEmailInboxOtp200Response
        /// </summary>
        [Fact]
        public void GetEmailInboxOtp200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetEmailInboxOtp200Response
            //Assert.IsType<GetEmailInboxOtp200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
