/*
 * ProgrammableInbox Email Inboxes API
 *
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using ProgrammableInbox.Sdk.Api;
using ProgrammableInbox.Sdk.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace ProgrammableInbox.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing EmailInboxesApi
    /// </summary>
    public sealed class EmailInboxesApiTests : ApiTestsBase
    {
        private readonly IEmailInboxesApi _instance;

        public EmailInboxesApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IEmailInboxesApi>();
        }

        /// <summary>
        /// Test CreateEmailInbox
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateEmailInboxAsyncTest()
        {
            CreateEmailInboxRequest createEmailInboxRequest = default!;
            var response = await _instance.CreateEmailInboxAsync(createEmailInboxRequest);
            var model = response.Created();
            Assert.IsType<CreateEmailInbox201Response>(model);
        }

        /// <summary>
        /// Test DeleteEmailInbox
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeleteEmailInboxAsyncTest()
        {
            string id = default!;
            await _instance.DeleteEmailInboxAsync(id);
        }

        /// <summary>
        /// Test GetEmailInbox
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetEmailInboxAsyncTest()
        {
            string id = default!;
            var response = await _instance.GetEmailInboxAsync(id);
            var model = response.Ok();
            Assert.IsType<GetEmailInbox200Response>(model);
        }

        /// <summary>
        /// Test GetEmailInboxMessages
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetEmailInboxMessagesAsyncTest()
        {
            string id = default!;
            Client.Option<string> cursor = default!;
            Client.Option<int> limit = default!;
            Client.Option<string> threadId = default!;
            Client.Option<bool> grouped = default!;
            Client.Option<string> q = default!;
            Client.Option<string> from = default!;
            Client.Option<List<string>> tags = default!;
            Client.Option<List<string>> categories = default!;
            var response = await _instance.GetEmailInboxMessagesAsync(id, cursor, limit, threadId, grouped, q, from, tags, categories);
            var model = response.Ok();
            Assert.IsType<GetEmailInboxMessages200Response>(model);
        }

        /// <summary>
        /// Test GetEmailMessage
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetEmailMessageAsyncTest()
        {
            string id = default!;
            string messageId = default!;
            var response = await _instance.GetEmailMessageAsync(id, messageId);
            var model = response.Ok();
            Assert.IsType<GetEmailMessage200Response>(model);
        }

        /// <summary>
        /// Test ListEmailInboxes
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ListEmailInboxesAsyncTest()
        {
            Client.Option<string> organizationId = default!;
            var response = await _instance.ListEmailInboxesAsync(organizationId);
            var model = response.Ok();
            Assert.IsType<ListEmailInboxes200Response>(model);
        }

        /// <summary>
        /// Test UpdateEmailInbox
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UpdateEmailInboxAsyncTest()
        {
            string id = default!;
            UpdateEmailInboxRequest updateEmailInboxRequest = default!;
            var response = await _instance.UpdateEmailInboxAsync(id, updateEmailInboxRequest);
            var model = response.Ok();
            Assert.IsType<CreateEmailInbox201Response>(model);
        }
    }
}
