/*
 * ProgrammableInbox Email Inboxes API
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.programmableinbox.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetEmailInboxOtp200ResponseData
 */
class GetEmailInboxOtp200ResponseDataTest {
    private final GetEmailInboxOtp200ResponseData model = new GetEmailInboxOtp200ResponseData();

    /**
     * Model tests for GetEmailInboxOtp200ResponseData
     */
    @Test
    void testGetEmailInboxOtp200ResponseData() {
        // TODO: test GetEmailInboxOtp200ResponseData
    }

    /**
     * Test the property 'otp'
     */
    @Test
    void otpTest() {
        // TODO: test otp
    }

    /**
     * Test the property 'receivedAt'
     */
    @Test
    void receivedAtTest() {
        // TODO: test receivedAt
    }

    /**
     * Test the property 'messageId'
     */
    @Test
    void messageIdTest() {
        // TODO: test messageId
    }

    /**
     * Test the property 'from'
     */
    @Test
    void fromTest() {
        // TODO: test from
    }

}
