/*
 * ProgrammableInbox Email Inboxes API
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.programmableinbox.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.programmableinbox.sdk.model.GetEmailInboxMessages200ResponseDataMessagesInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetEmailInboxMessages200ResponseData
 */
class GetEmailInboxMessages200ResponseDataTest {
    private final GetEmailInboxMessages200ResponseData model = new GetEmailInboxMessages200ResponseData();

    /**
     * Model tests for GetEmailInboxMessages200ResponseData
     */
    @Test
    void testGetEmailInboxMessages200ResponseData() {
        // TODO: test GetEmailInboxMessages200ResponseData
    }

    /**
     * Test the property 'messages'
     */
    @Test
    void messagesTest() {
        // TODO: test messages
    }

    /**
     * Test the property 'nextCursor'
     */
    @Test
    void nextCursorTest() {
        // TODO: test nextCursor
    }

    /**
     * Test the property 'hasMore'
     */
    @Test
    void hasMoreTest() {
        // TODO: test hasMore
    }

}
