/*
 * ProgrammableInbox Email Inboxes API
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.programmableinbox.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetEmailInboxMessages200ResponseDataMessagesInner
 */
class GetEmailInboxMessages200ResponseDataMessagesInnerTest {
    private final GetEmailInboxMessages200ResponseDataMessagesInner model = new GetEmailInboxMessages200ResponseDataMessagesInner();

    /**
     * Model tests for GetEmailInboxMessages200ResponseDataMessagesInner
     */
    @Test
    void testGetEmailInboxMessages200ResponseDataMessagesInner() {
        // TODO: test GetEmailInboxMessages200ResponseDataMessagesInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'threadId'
     */
    @Test
    void threadIdTest() {
        // TODO: test threadId
    }

    /**
     * Test the property 'parentMessageId'
     */
    @Test
    void parentMessageIdTest() {
        // TODO: test parentMessageId
    }

    /**
     * Test the property 'subject'
     */
    @Test
    void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'from'
     */
    @Test
    void fromTest() {
        // TODO: test from
    }

    /**
     * Test the property 'to'
     */
    @Test
    void toTest() {
        // TODO: test to
    }

    /**
     * Test the property 'cc'
     */
    @Test
    void ccTest() {
        // TODO: test cc
    }

    /**
     * Test the property 'bcc'
     */
    @Test
    void bccTest() {
        // TODO: test bcc
    }

    /**
     * Test the property 'text'
     */
    @Test
    void textTest() {
        // TODO: test text
    }

    /**
     * Test the property 'html'
     */
    @Test
    void htmlTest() {
        // TODO: test html
    }

    /**
     * Test the property 'bodyText'
     */
    @Test
    void bodyTextTest() {
        // TODO: test bodyText
    }

    /**
     * Test the property 'isStarred'
     */
    @Test
    void isStarredTest() {
        // TODO: test isStarred
    }

    /**
     * Test the property 'tags'
     */
    @Test
    void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'categories'
     */
    @Test
    void categoriesTest() {
        // TODO: test categories
    }

    /**
     * Test the property 'extractedOtp'
     */
    @Test
    void extractedOtpTest() {
        // TODO: test extractedOtp
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'threadCount'
     */
    @Test
    void threadCountTest() {
        // TODO: test threadCount
    }

}
