/*
 * ProgrammableInbox Email Inboxes API
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.programmableinbox.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.programmableinbox.sdk.model.EmailMessage;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.programmableinbox.sdk.ApiClient;
/**
 * GetEmailInboxOtp200ResponseData
 */
@JsonPropertyOrder({
  GetEmailInboxOtp200ResponseData.JSON_PROPERTY_OTP,
  GetEmailInboxOtp200ResponseData.JSON_PROPERTY_MESSAGE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class GetEmailInboxOtp200ResponseData {
  public static final String JSON_PROPERTY_OTP = "otp";
  @javax.annotation.Nonnull
  private String otp;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @javax.annotation.Nonnull
  private EmailMessage message;

  public GetEmailInboxOtp200ResponseData() { 
  }

  public GetEmailInboxOtp200ResponseData otp(@javax.annotation.Nonnull String otp) {
    this.otp = otp;
    return this;
  }

  /**
   * Get otp
   * @return otp
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OTP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getOtp() {
    return otp;
  }


  @JsonProperty(value = JSON_PROPERTY_OTP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOtp(@javax.annotation.Nonnull String otp) {
    this.otp = otp;
  }


  public GetEmailInboxOtp200ResponseData message(@javax.annotation.Nonnull EmailMessage message) {
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public EmailMessage getMessage() {
    return message;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessage(@javax.annotation.Nonnull EmailMessage message) {
    this.message = message;
  }


  /**
   * Return true if this getEmailInboxOtp_200_response_data object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetEmailInboxOtp200ResponseData getEmailInboxOtp200ResponseData = (GetEmailInboxOtp200ResponseData) o;
    return Objects.equals(this.otp, getEmailInboxOtp200ResponseData.otp) &&
        Objects.equals(this.message, getEmailInboxOtp200ResponseData.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(otp, message);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetEmailInboxOtp200ResponseData {\n");
    sb.append("    otp: ").append(toIndentedString(otp)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `otp` to the URL query string
    if (getOtp() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sotp%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOtp()))));
    }

    // add `message` to the URL query string
    if (getMessage() != null) {
      joiner.add(getMessage().toUrlQueryString(prefix + "message" + suffix));
    }

    return joiner.toString();
  }
}

