/*
 * ProgrammableInbox Email Inboxes API
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.programmableinbox.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.programmableinbox.sdk.ApiClient;
/**
 * GetEmailInboxMessages200ResponseDataMessagesInner
 */
@JsonPropertyOrder({
  GetEmailInboxMessages200ResponseDataMessagesInner.JSON_PROPERTY_ID,
  GetEmailInboxMessages200ResponseDataMessagesInner.JSON_PROPERTY_THREAD_ID,
  GetEmailInboxMessages200ResponseDataMessagesInner.JSON_PROPERTY_PARENT_MESSAGE_ID,
  GetEmailInboxMessages200ResponseDataMessagesInner.JSON_PROPERTY_SUBJECT,
  GetEmailInboxMessages200ResponseDataMessagesInner.JSON_PROPERTY_FROM,
  GetEmailInboxMessages200ResponseDataMessagesInner.JSON_PROPERTY_TO,
  GetEmailInboxMessages200ResponseDataMessagesInner.JSON_PROPERTY_CC,
  GetEmailInboxMessages200ResponseDataMessagesInner.JSON_PROPERTY_BCC,
  GetEmailInboxMessages200ResponseDataMessagesInner.JSON_PROPERTY_TEXT,
  GetEmailInboxMessages200ResponseDataMessagesInner.JSON_PROPERTY_HTML,
  GetEmailInboxMessages200ResponseDataMessagesInner.JSON_PROPERTY_BODY_TEXT,
  GetEmailInboxMessages200ResponseDataMessagesInner.JSON_PROPERTY_IS_STARRED,
  GetEmailInboxMessages200ResponseDataMessagesInner.JSON_PROPERTY_TAGS,
  GetEmailInboxMessages200ResponseDataMessagesInner.JSON_PROPERTY_CATEGORIES,
  GetEmailInboxMessages200ResponseDataMessagesInner.JSON_PROPERTY_EXTRACTED_OTP,
  GetEmailInboxMessages200ResponseDataMessagesInner.JSON_PROPERTY_CREATED_AT,
  GetEmailInboxMessages200ResponseDataMessagesInner.JSON_PROPERTY_THREAD_COUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class GetEmailInboxMessages200ResponseDataMessagesInner {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_THREAD_ID = "threadId";
  @javax.annotation.Nonnull
  private String threadId;

  public static final String JSON_PROPERTY_PARENT_MESSAGE_ID = "parentMessageId";
  @javax.annotation.Nullable
  private String parentMessageId;

  public static final String JSON_PROPERTY_SUBJECT = "subject";
  @javax.annotation.Nonnull
  private String subject;

  public static final String JSON_PROPERTY_FROM = "from";
  @javax.annotation.Nonnull
  private String from;

  public static final String JSON_PROPERTY_TO = "to";
  @javax.annotation.Nonnull
  private List<String> to = new ArrayList<>();

  public static final String JSON_PROPERTY_CC = "cc";
  @javax.annotation.Nonnull
  private List<String> cc = new ArrayList<>();

  public static final String JSON_PROPERTY_BCC = "bcc";
  @javax.annotation.Nonnull
  private List<String> bcc = new ArrayList<>();

  public static final String JSON_PROPERTY_TEXT = "text";
  @javax.annotation.Nonnull
  private String text;

  public static final String JSON_PROPERTY_HTML = "html";
  @javax.annotation.Nonnull
  private String html;

  public static final String JSON_PROPERTY_BODY_TEXT = "bodyText";
  @javax.annotation.Nullable
  private String bodyText;

  public static final String JSON_PROPERTY_IS_STARRED = "isStarred";
  @javax.annotation.Nonnull
  private Boolean isStarred;

  public static final String JSON_PROPERTY_TAGS = "tags";
  @javax.annotation.Nonnull
  private List<String> tags = new ArrayList<>();

  public static final String JSON_PROPERTY_CATEGORIES = "categories";
  @javax.annotation.Nonnull
  private List<String> categories = new ArrayList<>();

  public static final String JSON_PROPERTY_EXTRACTED_OTP = "extractedOtp";
  @javax.annotation.Nullable
  private String extractedOtp;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_THREAD_COUNT = "threadCount";
  @javax.annotation.Nullable
  private Integer threadCount;

  public GetEmailInboxMessages200ResponseDataMessagesInner() { 
  }

  public GetEmailInboxMessages200ResponseDataMessagesInner id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public GetEmailInboxMessages200ResponseDataMessagesInner threadId(@javax.annotation.Nonnull String threadId) {
    this.threadId = threadId;
    return this;
  }

  /**
   * Get threadId
   * @return threadId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_THREAD_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getThreadId() {
    return threadId;
  }


  @JsonProperty(value = JSON_PROPERTY_THREAD_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setThreadId(@javax.annotation.Nonnull String threadId) {
    this.threadId = threadId;
  }


  public GetEmailInboxMessages200ResponseDataMessagesInner parentMessageId(@javax.annotation.Nullable String parentMessageId) {
    this.parentMessageId = parentMessageId;
    return this;
  }

  /**
   * Get parentMessageId
   * @return parentMessageId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PARENT_MESSAGE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getParentMessageId() {
    return parentMessageId;
  }


  @JsonProperty(value = JSON_PROPERTY_PARENT_MESSAGE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setParentMessageId(@javax.annotation.Nullable String parentMessageId) {
    this.parentMessageId = parentMessageId;
  }


  public GetEmailInboxMessages200ResponseDataMessagesInner subject(@javax.annotation.Nonnull String subject) {
    this.subject = subject;
    return this;
  }

  /**
   * Get subject
   * @return subject
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SUBJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSubject() {
    return subject;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubject(@javax.annotation.Nonnull String subject) {
    this.subject = subject;
  }


  public GetEmailInboxMessages200ResponseDataMessagesInner from(@javax.annotation.Nonnull String from) {
    this.from = from;
    return this;
  }

  /**
   * Get from
   * @return from
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FROM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getFrom() {
    return from;
  }


  @JsonProperty(value = JSON_PROPERTY_FROM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFrom(@javax.annotation.Nonnull String from) {
    this.from = from;
  }


  public GetEmailInboxMessages200ResponseDataMessagesInner to(@javax.annotation.Nonnull List<String> to) {
    this.to = to;
    return this;
  }

  public GetEmailInboxMessages200ResponseDataMessagesInner addToItem(String toItem) {
    if (this.to == null) {
      this.to = new ArrayList<>();
    }
    this.to.add(toItem);
    return this;
  }

  /**
   * Get to
   * @return to
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getTo() {
    return to;
  }


  @JsonProperty(value = JSON_PROPERTY_TO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTo(@javax.annotation.Nonnull List<String> to) {
    this.to = to;
  }


  public GetEmailInboxMessages200ResponseDataMessagesInner cc(@javax.annotation.Nonnull List<String> cc) {
    this.cc = cc;
    return this;
  }

  public GetEmailInboxMessages200ResponseDataMessagesInner addCcItem(String ccItem) {
    if (this.cc == null) {
      this.cc = new ArrayList<>();
    }
    this.cc.add(ccItem);
    return this;
  }

  /**
   * Get cc
   * @return cc
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CC, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getCc() {
    return cc;
  }


  @JsonProperty(value = JSON_PROPERTY_CC, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCc(@javax.annotation.Nonnull List<String> cc) {
    this.cc = cc;
  }


  public GetEmailInboxMessages200ResponseDataMessagesInner bcc(@javax.annotation.Nonnull List<String> bcc) {
    this.bcc = bcc;
    return this;
  }

  public GetEmailInboxMessages200ResponseDataMessagesInner addBccItem(String bccItem) {
    if (this.bcc == null) {
      this.bcc = new ArrayList<>();
    }
    this.bcc.add(bccItem);
    return this;
  }

  /**
   * Get bcc
   * @return bcc
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BCC, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getBcc() {
    return bcc;
  }


  @JsonProperty(value = JSON_PROPERTY_BCC, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBcc(@javax.annotation.Nonnull List<String> bcc) {
    this.bcc = bcc;
  }


  public GetEmailInboxMessages200ResponseDataMessagesInner text(@javax.annotation.Nonnull String text) {
    this.text = text;
    return this;
  }

  /**
   * Get text
   * @return text
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TEXT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getText() {
    return text;
  }


  @JsonProperty(value = JSON_PROPERTY_TEXT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setText(@javax.annotation.Nonnull String text) {
    this.text = text;
  }


  public GetEmailInboxMessages200ResponseDataMessagesInner html(@javax.annotation.Nonnull String html) {
    this.html = html;
    return this;
  }

  /**
   * Get html
   * @return html
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_HTML, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getHtml() {
    return html;
  }


  @JsonProperty(value = JSON_PROPERTY_HTML, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHtml(@javax.annotation.Nonnull String html) {
    this.html = html;
  }


  public GetEmailInboxMessages200ResponseDataMessagesInner bodyText(@javax.annotation.Nullable String bodyText) {
    this.bodyText = bodyText;
    return this;
  }

  /**
   * Plain text of the body, and the field the &#x60;q&#x60; parameter searches. Equal to &#x60;text&#x60; when the sender supplied a text part, otherwise extracted from &#x60;html&#x60;. Null for messages stored before this field existed.
   * @return bodyText
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BODY_TEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getBodyText() {
    return bodyText;
  }


  @JsonProperty(value = JSON_PROPERTY_BODY_TEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBodyText(@javax.annotation.Nullable String bodyText) {
    this.bodyText = bodyText;
  }


  public GetEmailInboxMessages200ResponseDataMessagesInner isStarred(@javax.annotation.Nonnull Boolean isStarred) {
    this.isStarred = isStarred;
    return this;
  }

  /**
   * Get isStarred
   * @return isStarred
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_IS_STARRED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getIsStarred() {
    return isStarred;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_STARRED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsStarred(@javax.annotation.Nonnull Boolean isStarred) {
    this.isStarred = isStarred;
  }


  public GetEmailInboxMessages200ResponseDataMessagesInner tags(@javax.annotation.Nonnull List<String> tags) {
    this.tags = tags;
    return this;
  }

  public GetEmailInboxMessages200ResponseDataMessagesInner addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TAGS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getTags() {
    return tags;
  }


  @JsonProperty(value = JSON_PROPERTY_TAGS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTags(@javax.annotation.Nonnull List<String> tags) {
    this.tags = tags;
  }


  public GetEmailInboxMessages200ResponseDataMessagesInner categories(@javax.annotation.Nonnull List<String> categories) {
    this.categories = categories;
    return this;
  }

  public GetEmailInboxMessages200ResponseDataMessagesInner addCategoriesItem(String categoriesItem) {
    if (this.categories == null) {
      this.categories = new ArrayList<>();
    }
    this.categories.add(categoriesItem);
    return this;
  }

  /**
   * Categories assigned to the message. Matched by the &#x60;categories&#x60; parameter.
   * @return categories
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CATEGORIES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getCategories() {
    return categories;
  }


  @JsonProperty(value = JSON_PROPERTY_CATEGORIES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCategories(@javax.annotation.Nonnull List<String> categories) {
    this.categories = categories;
  }


  public GetEmailInboxMessages200ResponseDataMessagesInner extractedOtp(@javax.annotation.Nullable String extractedOtp) {
    this.extractedOtp = extractedOtp;
    return this;
  }

  /**
   * One-time code parsed from the message body. Derived from text/html, which the same email_messages:read scope already returns.
   * @return extractedOtp
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXTRACTED_OTP, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getExtractedOtp() {
    return extractedOtp;
  }


  @JsonProperty(value = JSON_PROPERTY_EXTRACTED_OTP, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExtractedOtp(@javax.annotation.Nullable String extractedOtp) {
    this.extractedOtp = extractedOtp;
  }


  public GetEmailInboxMessages200ResponseDataMessagesInner createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public GetEmailInboxMessages200ResponseDataMessagesInner threadCount(@javax.annotation.Nullable Integer threadCount) {
    this.threadCount = threadCount;
    return this;
  }

  /**
   * Number of messages in the thread (present only in grouped mode)
   * @return threadCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_THREAD_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getThreadCount() {
    return threadCount;
  }


  @JsonProperty(value = JSON_PROPERTY_THREAD_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThreadCount(@javax.annotation.Nullable Integer threadCount) {
    this.threadCount = threadCount;
  }


  /**
   * Return true if this getEmailInboxMessages_200_response_data_messages_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetEmailInboxMessages200ResponseDataMessagesInner getEmailInboxMessages200ResponseDataMessagesInner = (GetEmailInboxMessages200ResponseDataMessagesInner) o;
    return Objects.equals(this.id, getEmailInboxMessages200ResponseDataMessagesInner.id) &&
        Objects.equals(this.threadId, getEmailInboxMessages200ResponseDataMessagesInner.threadId) &&
        Objects.equals(this.parentMessageId, getEmailInboxMessages200ResponseDataMessagesInner.parentMessageId) &&
        Objects.equals(this.subject, getEmailInboxMessages200ResponseDataMessagesInner.subject) &&
        Objects.equals(this.from, getEmailInboxMessages200ResponseDataMessagesInner.from) &&
        Objects.equals(this.to, getEmailInboxMessages200ResponseDataMessagesInner.to) &&
        Objects.equals(this.cc, getEmailInboxMessages200ResponseDataMessagesInner.cc) &&
        Objects.equals(this.bcc, getEmailInboxMessages200ResponseDataMessagesInner.bcc) &&
        Objects.equals(this.text, getEmailInboxMessages200ResponseDataMessagesInner.text) &&
        Objects.equals(this.html, getEmailInboxMessages200ResponseDataMessagesInner.html) &&
        Objects.equals(this.bodyText, getEmailInboxMessages200ResponseDataMessagesInner.bodyText) &&
        Objects.equals(this.isStarred, getEmailInboxMessages200ResponseDataMessagesInner.isStarred) &&
        Objects.equals(this.tags, getEmailInboxMessages200ResponseDataMessagesInner.tags) &&
        Objects.equals(this.categories, getEmailInboxMessages200ResponseDataMessagesInner.categories) &&
        Objects.equals(this.extractedOtp, getEmailInboxMessages200ResponseDataMessagesInner.extractedOtp) &&
        Objects.equals(this.createdAt, getEmailInboxMessages200ResponseDataMessagesInner.createdAt) &&
        Objects.equals(this.threadCount, getEmailInboxMessages200ResponseDataMessagesInner.threadCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, threadId, parentMessageId, subject, from, to, cc, bcc, text, html, bodyText, isStarred, tags, categories, extractedOtp, createdAt, threadCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetEmailInboxMessages200ResponseDataMessagesInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    threadId: ").append(toIndentedString(threadId)).append("\n");
    sb.append("    parentMessageId: ").append(toIndentedString(parentMessageId)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    cc: ").append(toIndentedString(cc)).append("\n");
    sb.append("    bcc: ").append(toIndentedString(bcc)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    html: ").append(toIndentedString(html)).append("\n");
    sb.append("    bodyText: ").append(toIndentedString(bodyText)).append("\n");
    sb.append("    isStarred: ").append(toIndentedString(isStarred)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    categories: ").append(toIndentedString(categories)).append("\n");
    sb.append("    extractedOtp: ").append(toIndentedString(extractedOtp)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    threadCount: ").append(toIndentedString(threadCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `threadId` to the URL query string
    if (getThreadId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sthreadId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getThreadId()))));
    }

    // add `parentMessageId` to the URL query string
    if (getParentMessageId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sparentMessageId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getParentMessageId()))));
    }

    // add `subject` to the URL query string
    if (getSubject() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssubject%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSubject()))));
    }

    // add `from` to the URL query string
    if (getFrom() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfrom%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFrom()))));
    }

    // add `to` to the URL query string
    if (getTo() != null) {
      for (int i = 0; i < getTo().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sto%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getTo().get(i)))));
      }
    }

    // add `cc` to the URL query string
    if (getCc() != null) {
      for (int i = 0; i < getCc().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%scc%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getCc().get(i)))));
      }
    }

    // add `bcc` to the URL query string
    if (getBcc() != null) {
      for (int i = 0; i < getBcc().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sbcc%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getBcc().get(i)))));
      }
    }

    // add `text` to the URL query string
    if (getText() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stext%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getText()))));
    }

    // add `html` to the URL query string
    if (getHtml() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shtml%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHtml()))));
    }

    // add `bodyText` to the URL query string
    if (getBodyText() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbodyText%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBodyText()))));
    }

    // add `isStarred` to the URL query string
    if (getIsStarred() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sisStarred%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsStarred()))));
    }

    // add `tags` to the URL query string
    if (getTags() != null) {
      for (int i = 0; i < getTags().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%stags%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getTags().get(i)))));
      }
    }

    // add `categories` to the URL query string
    if (getCategories() != null) {
      for (int i = 0; i < getCategories().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%scategories%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getCategories().get(i)))));
      }
    }

    // add `extractedOtp` to the URL query string
    if (getExtractedOtp() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sextractedOtp%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExtractedOtp()))));
    }

    // add `createdAt` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `threadCount` to the URL query string
    if (getThreadCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sthreadCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getThreadCount()))));
    }

    return joiner.toString();
  }
}

