/*
 * ProgrammableInbox Email Inboxes API
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.programmableinbox.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.programmableinbox.sdk.model.GetEmailInboxMessages200ResponseDataMessagesInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.programmableinbox.sdk.ApiClient;
/**
 * GetEmailInboxMessages200ResponseData
 */
@JsonPropertyOrder({
  GetEmailInboxMessages200ResponseData.JSON_PROPERTY_MESSAGES,
  GetEmailInboxMessages200ResponseData.JSON_PROPERTY_NEXT_CURSOR,
  GetEmailInboxMessages200ResponseData.JSON_PROPERTY_HAS_MORE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class GetEmailInboxMessages200ResponseData {
  public static final String JSON_PROPERTY_MESSAGES = "messages";
  @javax.annotation.Nonnull
  private List<GetEmailInboxMessages200ResponseDataMessagesInner> messages = new ArrayList<>();

  public static final String JSON_PROPERTY_NEXT_CURSOR = "nextCursor";
  @javax.annotation.Nullable
  private String nextCursor;

  public static final String JSON_PROPERTY_HAS_MORE = "hasMore";
  @javax.annotation.Nonnull
  private Boolean hasMore;

  public GetEmailInboxMessages200ResponseData() { 
  }

  public GetEmailInboxMessages200ResponseData messages(@javax.annotation.Nonnull List<GetEmailInboxMessages200ResponseDataMessagesInner> messages) {
    this.messages = messages;
    return this;
  }

  public GetEmailInboxMessages200ResponseData addMessagesItem(GetEmailInboxMessages200ResponseDataMessagesInner messagesItem) {
    if (this.messages == null) {
      this.messages = new ArrayList<>();
    }
    this.messages.add(messagesItem);
    return this;
  }

  /**
   * Get messages
   * @return messages
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<GetEmailInboxMessages200ResponseDataMessagesInner> getMessages() {
    return messages;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessages(@javax.annotation.Nonnull List<GetEmailInboxMessages200ResponseDataMessagesInner> messages) {
    this.messages = messages;
  }


  public GetEmailInboxMessages200ResponseData nextCursor(@javax.annotation.Nullable String nextCursor) {
    this.nextCursor = nextCursor;
    return this;
  }

  /**
   * Cursor for the next page, or null if there are no more results
   * @return nextCursor
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NEXT_CURSOR, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getNextCursor() {
    return nextCursor;
  }


  @JsonProperty(value = JSON_PROPERTY_NEXT_CURSOR, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNextCursor(@javax.annotation.Nullable String nextCursor) {
    this.nextCursor = nextCursor;
  }


  public GetEmailInboxMessages200ResponseData hasMore(@javax.annotation.Nonnull Boolean hasMore) {
    this.hasMore = hasMore;
    return this;
  }

  /**
   * True if more results exist beyond this page
   * @return hasMore
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_HAS_MORE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getHasMore() {
    return hasMore;
  }


  @JsonProperty(value = JSON_PROPERTY_HAS_MORE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHasMore(@javax.annotation.Nonnull Boolean hasMore) {
    this.hasMore = hasMore;
  }


  /**
   * Return true if this getEmailInboxMessages_200_response_data object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetEmailInboxMessages200ResponseData getEmailInboxMessages200ResponseData = (GetEmailInboxMessages200ResponseData) o;
    return Objects.equals(this.messages, getEmailInboxMessages200ResponseData.messages) &&
        Objects.equals(this.nextCursor, getEmailInboxMessages200ResponseData.nextCursor) &&
        Objects.equals(this.hasMore, getEmailInboxMessages200ResponseData.hasMore);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messages, nextCursor, hasMore);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetEmailInboxMessages200ResponseData {\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("    nextCursor: ").append(toIndentedString(nextCursor)).append("\n");
    sb.append("    hasMore: ").append(toIndentedString(hasMore)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `messages` to the URL query string
    if (getMessages() != null) {
      for (int i = 0; i < getMessages().size(); i++) {
        if (getMessages().get(i) != null) {
          joiner.add(getMessages().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%smessages%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `nextCursor` to the URL query string
    if (getNextCursor() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%snextCursor%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNextCursor()))));
    }

    // add `hasMore` to the URL query string
    if (getHasMore() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shasMore%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHasMore()))));
    }

    return joiner.toString();
  }
}

