/*
 * ProgrammableInbox Email Inboxes API
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.programmableinbox.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.programmableinbox.sdk.ApiClient;
/**
 * GetEmailInboxOtp200ResponseData
 */
@JsonPropertyOrder({
  GetEmailInboxOtp200ResponseData.JSON_PROPERTY_OTP,
  GetEmailInboxOtp200ResponseData.JSON_PROPERTY_RECEIVED_AT,
  GetEmailInboxOtp200ResponseData.JSON_PROPERTY_MESSAGE_ID,
  GetEmailInboxOtp200ResponseData.JSON_PROPERTY_FROM
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class GetEmailInboxOtp200ResponseData {
  public static final String JSON_PROPERTY_OTP = "otp";
  @javax.annotation.Nonnull
  private String otp;

  public static final String JSON_PROPERTY_RECEIVED_AT = "receivedAt";
  @javax.annotation.Nonnull
  private OffsetDateTime receivedAt;

  public static final String JSON_PROPERTY_MESSAGE_ID = "messageId";
  @javax.annotation.Nonnull
  private String messageId;

  public static final String JSON_PROPERTY_FROM = "from";
  @javax.annotation.Nonnull
  private String from;

  public GetEmailInboxOtp200ResponseData() { 
  }

  public GetEmailInboxOtp200ResponseData otp(@javax.annotation.Nonnull String otp) {
    this.otp = otp;
    return this;
  }

  /**
   * Get otp
   * @return otp
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OTP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getOtp() {
    return otp;
  }


  @JsonProperty(value = JSON_PROPERTY_OTP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOtp(@javax.annotation.Nonnull String otp) {
    this.otp = otp;
  }


  public GetEmailInboxOtp200ResponseData receivedAt(@javax.annotation.Nonnull OffsetDateTime receivedAt) {
    this.receivedAt = receivedAt;
    return this;
  }

  /**
   * Get receivedAt
   * @return receivedAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RECEIVED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getReceivedAt() {
    return receivedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_RECEIVED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReceivedAt(@javax.annotation.Nonnull OffsetDateTime receivedAt) {
    this.receivedAt = receivedAt;
  }


  public GetEmailInboxOtp200ResponseData messageId(@javax.annotation.Nonnull String messageId) {
    this.messageId = messageId;
    return this;
  }

  /**
   * Get messageId
   * @return messageId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getMessageId() {
    return messageId;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessageId(@javax.annotation.Nonnull String messageId) {
    this.messageId = messageId;
  }


  public GetEmailInboxOtp200ResponseData from(@javax.annotation.Nonnull String from) {
    this.from = from;
    return this;
  }

  /**
   * Get from
   * @return from
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FROM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getFrom() {
    return from;
  }


  @JsonProperty(value = JSON_PROPERTY_FROM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFrom(@javax.annotation.Nonnull String from) {
    this.from = from;
  }


  /**
   * Return true if this getEmailInboxOtp_200_response_data object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetEmailInboxOtp200ResponseData getEmailInboxOtp200ResponseData = (GetEmailInboxOtp200ResponseData) o;
    return Objects.equals(this.otp, getEmailInboxOtp200ResponseData.otp) &&
        Objects.equals(this.receivedAt, getEmailInboxOtp200ResponseData.receivedAt) &&
        Objects.equals(this.messageId, getEmailInboxOtp200ResponseData.messageId) &&
        Objects.equals(this.from, getEmailInboxOtp200ResponseData.from);
  }

  @Override
  public int hashCode() {
    return Objects.hash(otp, receivedAt, messageId, from);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetEmailInboxOtp200ResponseData {\n");
    sb.append("    otp: ").append(toIndentedString(otp)).append("\n");
    sb.append("    receivedAt: ").append(toIndentedString(receivedAt)).append("\n");
    sb.append("    messageId: ").append(toIndentedString(messageId)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `otp` to the URL query string
    if (getOtp() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sotp%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOtp()))));
    }

    // add `receivedAt` to the URL query string
    if (getReceivedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sreceivedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReceivedAt()))));
    }

    // add `messageId` to the URL query string
    if (getMessageId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smessageId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMessageId()))));
    }

    // add `from` to the URL query string
    if (getFrom() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfrom%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFrom()))));
    }

    return joiner.toString();
  }
}

