# coding: utf-8

# flake8: noqa

"""
    ProgrammableInbox Email Inboxes API

    Email inbox management endpoints with API key support

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.1.0"

# Define package exports
__all__ = [
    "EmailInboxesApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "CreateEmailInbox201Response",
    "CreateEmailInboxRequest",
    "EmailInbox",
    "EmailMessage",
    "ErrorResponse",
    "GetEmailInbox200Response",
    "GetEmailInboxMessages200Response",
    "GetEmailInboxMessages200ResponseData",
    "GetEmailInboxMessages200ResponseDataMessagesInner",
    "GetEmailMessage200Response",
    "ListEmailInboxes200Response",
    "UpdateEmailInboxRequest",
]

# import apis into sdk package
from programmableinbox.api.email_inboxes_api import EmailInboxesApi as EmailInboxesApi

# import ApiClient
from programmableinbox.api_response import ApiResponse as ApiResponse
from programmableinbox.api_client import ApiClient as ApiClient
from programmableinbox.configuration import Configuration as Configuration
from programmableinbox.exceptions import OpenApiException as OpenApiException
from programmableinbox.exceptions import ApiTypeError as ApiTypeError
from programmableinbox.exceptions import ApiValueError as ApiValueError
from programmableinbox.exceptions import ApiKeyError as ApiKeyError
from programmableinbox.exceptions import ApiAttributeError as ApiAttributeError
from programmableinbox.exceptions import ApiException as ApiException

# import models into sdk package
from programmableinbox.models.create_email_inbox201_response import CreateEmailInbox201Response as CreateEmailInbox201Response
from programmableinbox.models.create_email_inbox_request import CreateEmailInboxRequest as CreateEmailInboxRequest
from programmableinbox.models.email_inbox import EmailInbox as EmailInbox
from programmableinbox.models.email_message import EmailMessage as EmailMessage
from programmableinbox.models.error_response import ErrorResponse as ErrorResponse
from programmableinbox.models.get_email_inbox200_response import GetEmailInbox200Response as GetEmailInbox200Response
from programmableinbox.models.get_email_inbox_messages200_response import GetEmailInboxMessages200Response as GetEmailInboxMessages200Response
from programmableinbox.models.get_email_inbox_messages200_response_data import GetEmailInboxMessages200ResponseData as GetEmailInboxMessages200ResponseData
from programmableinbox.models.get_email_inbox_messages200_response_data_messages_inner import GetEmailInboxMessages200ResponseDataMessagesInner as GetEmailInboxMessages200ResponseDataMessagesInner
from programmableinbox.models.get_email_message200_response import GetEmailMessage200Response as GetEmailMessage200Response
from programmableinbox.models.list_email_inboxes200_response import ListEmailInboxes200Response as ListEmailInboxes200Response
from programmableinbox.models.update_email_inbox_request import UpdateEmailInboxRequest as UpdateEmailInboxRequest

