/*
 * ProgrammableInbox Email Inboxes API
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.programmableinbox.sdk.api;

import com.programmableinbox.sdk.ApiException;
import com.programmableinbox.sdk.model.CreateEmailInbox201Response;
import com.programmableinbox.sdk.model.CreateEmailInboxRequest;
import com.programmableinbox.sdk.model.ErrorResponse;
import com.programmableinbox.sdk.model.GetEmailInbox200Response;
import com.programmableinbox.sdk.model.GetEmailInboxMessages200Response;
import com.programmableinbox.sdk.model.GetEmailMessage200Response;
import com.programmableinbox.sdk.model.ListEmailInboxes200Response;
import com.programmableinbox.sdk.model.UpdateEmailInboxRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for EmailInboxesApi
 */
@Disabled
public class EmailInboxesApiTest {

    private final EmailInboxesApi api = new EmailInboxesApi();

    
    /**
     * Create an email inbox
     *
     * Claims a new email address and returns the inbox. The address must be on a domain this account can receive at, and is immutable once created. Requires API key with &#x60;email_inboxes:create&#x60; scope. The inbox is created in the organization the key is bound to; supplying a different &#x60;organizationId&#x60; is a 403 rather than a silently ignored field.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createEmailInboxTest() throws ApiException {
        CreateEmailInboxRequest createEmailInboxRequest = null;
        CreateEmailInbox201Response response = 
        api.createEmailInbox(createEmailInboxRequest);
        
        // TODO: test validations
    }
    
    /**
     * Delete an email inbox
     *
     * Soft-deletes the inbox and its messages in one transaction. The rows are retained and every read filters them out, so the data is recoverable — but the **address is retired permanently and can never be claimed again, by anyone including you**. Mail keeps being delivered to it, so releasing it would hand the next claimant your still-arriving messages. Requires API key with &#x60;email_inboxes:delete&#x60; scope, which is granted separately from create and update for exactly this reason.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteEmailInboxTest() throws ApiException {
        String id = null;
        
        api.deleteEmailInbox(id);
        
        // TODO: test validations
    }
    
    /**
     * Get an email inbox
     *
     * Returns a single email inbox by id, scoped to the organization the API key is bound to. Requires API key with &#x60;email_inboxes:read&#x60; scope.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEmailInboxTest() throws ApiException {
        String id = null;
        GetEmailInbox200Response response = 
        api.getEmailInbox(id);
        
        // TODO: test validations
    }
    
    /**
     * Get messages from an email inbox
     *
     * Returns messages for a specific email inbox with optional pagination and filtering. Requires API key with &#x60;email_messages:read&#x60; scope.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEmailInboxMessagesTest() throws ApiException {
        String id = null;
        String cursor = null;
        Integer limit = null;
        String threadId = null;
        Boolean grouped = null;
        String q = null;
        String from = null;
        List<String> tags = null;
        List<String> categories = null;
        GetEmailInboxMessages200Response response = 
        api.getEmailInboxMessages(id, cursor, limit, threadId, grouped, q, from, tags, categories);
        
        // TODO: test validations
    }
    
    /**
     * Get a single message
     *
     * Returns a specific message from an email inbox. Requires API key with &#x60;email_messages:read&#x60; scope.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEmailMessageTest() throws ApiException {
        String id = null;
        String messageId = null;
        GetEmailMessage200Response response = 
        api.getEmailMessage(id, messageId);
        
        // TODO: test validations
    }
    
    /**
     * List email inboxes
     *
     * Returns a list of email inboxes for the organization. Requires API key with &#x60;email_inboxes:read&#x60; scope.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listEmailInboxesTest() throws ApiException {
        String organizationId = null;
        ListEmailInboxes200Response response = 
        api.listEmailInboxes(organizationId);
        
        // TODO: test validations
    }
    
    /**
     * Rename an email inbox
     *
     * Updates an inbox display name. The address is immutable — submitting a different one is a 409; submitting the current one (after normalization) is an allowed no-op, so a client can PATCH a whole record back. Requires API key with &#x60;email_inboxes:update&#x60; scope.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateEmailInboxTest() throws ApiException {
        String id = null;
        UpdateEmailInboxRequest updateEmailInboxRequest = null;
        CreateEmailInbox201Response response = 
        api.updateEmailInbox(id, updateEmailInboxRequest);
        
        // TODO: test validations
    }
    
}
