// <auto-generated>
/*
 * ProgrammableInbox Email Inboxes API
 *
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using ProgrammableInbox.Sdk.Client;

namespace ProgrammableInbox.Sdk.Model
{
    /// <summary>
    /// An email inbox
    /// </summary>
    public partial class EmailInbox : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EmailInbox" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="organizationId">organizationId</param>
        /// <param name="email">email</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="updatedAt">updatedAt</param>
        /// <param name="name">name</param>
        [JsonConstructor]
        public EmailInbox(string id, string organizationId, string email, DateTime createdAt, DateTime updatedAt, string? name = default)
        {
            Id = id;
            OrganizationId = organizationId;
            Email = email;
            CreatedAt = createdAt;
            UpdatedAt = updatedAt;
            Name = name;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        /* <example>inbox-1</example> */
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets OrganizationId
        /// </summary>
        /* <example>org-1</example> */
        [JsonPropertyName("organizationId")]
        public string OrganizationId { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        /* <example>support@example.com</example> */
        [JsonPropertyName("email")]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("createdAt")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [JsonPropertyName("updatedAt")]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        /* <example>Support Inbox</example> */
        [JsonPropertyName("name")]
        public string? Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EmailInbox {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  OrganizationId: ").Append(OrganizationId).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EmailInbox" />
    /// </summary>
    public partial class EmailInboxJsonConverter : JsonConverter<EmailInbox>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="EmailInboxJsonConverter" /> class.
        /// </summary>
        public EmailInboxJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public string CreatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize UpdatedAt
        /// </summary>
        public string UpdatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="EmailInbox" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EmailInbox Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> organizationId = default;
            Option<string?> email = default;
            Option<DateTime?> createdAt = default;
            Option<DateTime?> updatedAt = default;
            Option<string?> name = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "organizationId":
                            organizationId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "email":
                            email = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "createdAt":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "updatedAt":
                            updatedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class EmailInbox.", nameof(id));

            if (!organizationId.IsSet)
                throw new ArgumentException("Property is required for class EmailInbox.", nameof(organizationId));

            if (!email.IsSet)
                throw new ArgumentException("Property is required for class EmailInbox.", nameof(email));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class EmailInbox.", nameof(createdAt));

            if (!updatedAt.IsSet)
                throw new ArgumentException("Property is required for class EmailInbox.", nameof(updatedAt));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class EmailInbox.", nameof(name));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class EmailInbox.");

            if (organizationId.IsSet && organizationId.Value == null)
                throw new ArgumentNullException(nameof(organizationId), "Property is not nullable for class EmailInbox.");

            if (email.IsSet && email.Value == null)
                throw new ArgumentNullException(nameof(email), "Property is not nullable for class EmailInbox.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class EmailInbox.");

            if (updatedAt.IsSet && updatedAt.Value == null)
                throw new ArgumentNullException(nameof(updatedAt), "Property is not nullable for class EmailInbox.");

            return new EmailInbox(id.Value!, organizationId.Value!, email.Value!, createdAt.Value!.Value!, updatedAt.Value!.Value!, name.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="EmailInbox" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="emailInbox"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EmailInbox emailInbox, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, emailInbox, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EmailInbox" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="emailInbox"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EmailInbox emailInbox, JsonSerializerOptions jsonSerializerOptions)
        {
            if (emailInbox.Id == null)
                throw new ArgumentNullException(nameof(emailInbox.Id), "Property is required for class EmailInbox.");

            if (emailInbox.OrganizationId == null)
                throw new ArgumentNullException(nameof(emailInbox.OrganizationId), "Property is required for class EmailInbox.");

            if (emailInbox.Email == null)
                throw new ArgumentNullException(nameof(emailInbox.Email), "Property is required for class EmailInbox.");

            writer.WriteString("id", emailInbox.Id);

            writer.WriteString("organizationId", emailInbox.OrganizationId);

            writer.WriteString("email", emailInbox.Email);

            writer.WriteString("createdAt", emailInbox.CreatedAt.ToString(CreatedAtFormat));

            writer.WriteString("updatedAt", emailInbox.UpdatedAt.ToString(UpdatedAtFormat));

            if (emailInbox.Name != null)
                writer.WriteString("name", emailInbox.Name);
            else
                writer.WriteNull("name");
        }
    }
}
