// <auto-generated>
/*
 * ProgrammableInbox Email Inboxes API
 *
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using ProgrammableInbox.Sdk.Client;

namespace ProgrammableInbox.Sdk.Model
{
    /// <summary>
    /// GetEmailInboxOtp200ResponseData
    /// </summary>
    public partial class GetEmailInboxOtp200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetEmailInboxOtp200ResponseData" /> class.
        /// </summary>
        /// <param name="otp">otp</param>
        /// <param name="receivedAt">receivedAt</param>
        /// <param name="messageId">messageId</param>
        /// <param name="from">from</param>
        [JsonConstructor]
        public GetEmailInboxOtp200ResponseData(string otp, DateTime receivedAt, string messageId, string from)
        {
            Otp = otp;
            ReceivedAt = receivedAt;
            MessageId = messageId;
            From = from;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Otp
        /// </summary>
        /* <example>123456</example> */
        [JsonPropertyName("otp")]
        public string Otp { get; set; }

        /// <summary>
        /// Gets or Sets ReceivedAt
        /// </summary>
        [JsonPropertyName("receivedAt")]
        public DateTime ReceivedAt { get; set; }

        /// <summary>
        /// Gets or Sets MessageId
        /// </summary>
        /* <example>msg-1</example> */
        [JsonPropertyName("messageId")]
        public string MessageId { get; set; }

        /// <summary>
        /// Gets or Sets From
        /// </summary>
        /* <example>noreply@example.com</example> */
        [JsonPropertyName("from")]
        public string From { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetEmailInboxOtp200ResponseData {\n");
            sb.Append("  Otp: ").Append(Otp).Append("\n");
            sb.Append("  ReceivedAt: ").Append(ReceivedAt).Append("\n");
            sb.Append("  MessageId: ").Append(MessageId).Append("\n");
            sb.Append("  From: ").Append(From).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetEmailInboxOtp200ResponseData" />
    /// </summary>
    public partial class GetEmailInboxOtp200ResponseDataJsonConverter : JsonConverter<GetEmailInboxOtp200ResponseData>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="GetEmailInboxOtp200ResponseDataJsonConverter" /> class.
        /// </summary>
        public GetEmailInboxOtp200ResponseDataJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize ReceivedAt
        /// </summary>
        public string ReceivedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="GetEmailInboxOtp200ResponseData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetEmailInboxOtp200ResponseData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> otp = default;
            Option<DateTime?> receivedAt = default;
            Option<string?> messageId = default;
            Option<string?> from = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "otp":
                            otp = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "receivedAt":
                            receivedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "messageId":
                            messageId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "from":
                            from = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!otp.IsSet)
                throw new ArgumentException("Property is required for class GetEmailInboxOtp200ResponseData.", nameof(otp));

            if (!receivedAt.IsSet)
                throw new ArgumentException("Property is required for class GetEmailInboxOtp200ResponseData.", nameof(receivedAt));

            if (!messageId.IsSet)
                throw new ArgumentException("Property is required for class GetEmailInboxOtp200ResponseData.", nameof(messageId));

            if (!from.IsSet)
                throw new ArgumentException("Property is required for class GetEmailInboxOtp200ResponseData.", nameof(from));

            if (otp.IsSet && otp.Value == null)
                throw new ArgumentNullException(nameof(otp), "Property is not nullable for class GetEmailInboxOtp200ResponseData.");

            if (receivedAt.IsSet && receivedAt.Value == null)
                throw new ArgumentNullException(nameof(receivedAt), "Property is not nullable for class GetEmailInboxOtp200ResponseData.");

            if (messageId.IsSet && messageId.Value == null)
                throw new ArgumentNullException(nameof(messageId), "Property is not nullable for class GetEmailInboxOtp200ResponseData.");

            if (from.IsSet && from.Value == null)
                throw new ArgumentNullException(nameof(from), "Property is not nullable for class GetEmailInboxOtp200ResponseData.");

            return new GetEmailInboxOtp200ResponseData(otp.Value!, receivedAt.Value!.Value!, messageId.Value!, from.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="GetEmailInboxOtp200ResponseData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getEmailInboxOtp200ResponseData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetEmailInboxOtp200ResponseData getEmailInboxOtp200ResponseData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getEmailInboxOtp200ResponseData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetEmailInboxOtp200ResponseData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getEmailInboxOtp200ResponseData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetEmailInboxOtp200ResponseData getEmailInboxOtp200ResponseData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getEmailInboxOtp200ResponseData.Otp == null)
                throw new ArgumentNullException(nameof(getEmailInboxOtp200ResponseData.Otp), "Property is required for class GetEmailInboxOtp200ResponseData.");

            if (getEmailInboxOtp200ResponseData.MessageId == null)
                throw new ArgumentNullException(nameof(getEmailInboxOtp200ResponseData.MessageId), "Property is required for class GetEmailInboxOtp200ResponseData.");

            if (getEmailInboxOtp200ResponseData.From == null)
                throw new ArgumentNullException(nameof(getEmailInboxOtp200ResponseData.From), "Property is required for class GetEmailInboxOtp200ResponseData.");

            writer.WriteString("otp", getEmailInboxOtp200ResponseData.Otp);

            writer.WriteString("receivedAt", getEmailInboxOtp200ResponseData.ReceivedAt.ToString(ReceivedAtFormat));

            writer.WriteString("messageId", getEmailInboxOtp200ResponseData.MessageId);

            writer.WriteString("from", getEmailInboxOtp200ResponseData.From);
        }
    }
}
