// <auto-generated>
/*
 * ProgrammableInbox Email Inboxes API
 *
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using ProgrammableInbox.Sdk.Client;

namespace ProgrammableInbox.Sdk.Model
{
    /// <summary>
    /// GetEmailInboxMessages200ResponseData
    /// </summary>
    public partial class GetEmailInboxMessages200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetEmailInboxMessages200ResponseData" /> class.
        /// </summary>
        /// <param name="messages">messages</param>
        /// <param name="hasMore">True if more results exist beyond this page</param>
        /// <param name="nextCursor">Cursor for the next page, or null if there are no more results</param>
        [JsonConstructor]
        public GetEmailInboxMessages200ResponseData(List<GetEmailInboxMessages200ResponseDataMessagesInner> messages, bool hasMore, string? nextCursor = default)
        {
            Messages = messages;
            HasMore = hasMore;
            NextCursor = nextCursor;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Messages
        /// </summary>
        [JsonPropertyName("messages")]
        public List<GetEmailInboxMessages200ResponseDataMessagesInner> Messages { get; set; }

        /// <summary>
        /// True if more results exist beyond this page
        /// </summary>
        /// <value>True if more results exist beyond this page</value>
        [JsonPropertyName("hasMore")]
        public bool HasMore { get; set; }

        /// <summary>
        /// Cursor for the next page, or null if there are no more results
        /// </summary>
        /// <value>Cursor for the next page, or null if there are no more results</value>
        [JsonPropertyName("nextCursor")]
        public string? NextCursor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetEmailInboxMessages200ResponseData {\n");
            sb.Append("  Messages: ").Append(Messages).Append("\n");
            sb.Append("  HasMore: ").Append(HasMore).Append("\n");
            sb.Append("  NextCursor: ").Append(NextCursor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetEmailInboxMessages200ResponseData" />
    /// </summary>
    public partial class GetEmailInboxMessages200ResponseDataJsonConverter : JsonConverter<GetEmailInboxMessages200ResponseData>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="GetEmailInboxMessages200ResponseDataJsonConverter" /> class.
        /// </summary>
        public GetEmailInboxMessages200ResponseDataJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="GetEmailInboxMessages200ResponseData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetEmailInboxMessages200ResponseData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<GetEmailInboxMessages200ResponseDataMessagesInner>?> messages = default;
            Option<bool?> hasMore = default;
            Option<string?> nextCursor = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "messages":
                            messages = new Option<List<GetEmailInboxMessages200ResponseDataMessagesInner>?>(JsonSerializer.Deserialize<List<GetEmailInboxMessages200ResponseDataMessagesInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "hasMore":
                            hasMore = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "nextCursor":
                            nextCursor = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!messages.IsSet)
                throw new ArgumentException("Property is required for class GetEmailInboxMessages200ResponseData.", nameof(messages));

            if (!hasMore.IsSet)
                throw new ArgumentException("Property is required for class GetEmailInboxMessages200ResponseData.", nameof(hasMore));

            if (!nextCursor.IsSet)
                throw new ArgumentException("Property is required for class GetEmailInboxMessages200ResponseData.", nameof(nextCursor));

            if (messages.IsSet && messages.Value == null)
                throw new ArgumentNullException(nameof(messages), "Property is not nullable for class GetEmailInboxMessages200ResponseData.");

            if (hasMore.IsSet && hasMore.Value == null)
                throw new ArgumentNullException(nameof(hasMore), "Property is not nullable for class GetEmailInboxMessages200ResponseData.");

            return new GetEmailInboxMessages200ResponseData(messages.Value!, hasMore.Value!.Value!, nextCursor.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="GetEmailInboxMessages200ResponseData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getEmailInboxMessages200ResponseData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetEmailInboxMessages200ResponseData getEmailInboxMessages200ResponseData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getEmailInboxMessages200ResponseData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetEmailInboxMessages200ResponseData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getEmailInboxMessages200ResponseData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetEmailInboxMessages200ResponseData getEmailInboxMessages200ResponseData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getEmailInboxMessages200ResponseData.Messages == null)
                throw new ArgumentNullException(nameof(getEmailInboxMessages200ResponseData.Messages), "Property is required for class GetEmailInboxMessages200ResponseData.");

            writer.WritePropertyName("messages");
            JsonSerializer.Serialize(writer, getEmailInboxMessages200ResponseData.Messages, jsonSerializerOptions);
            writer.WriteBoolean("hasMore", getEmailInboxMessages200ResponseData.HasMore);

            if (getEmailInboxMessages200ResponseData.NextCursor != null)
                writer.WriteString("nextCursor", getEmailInboxMessages200ResponseData.NextCursor);
            else
                writer.WriteNull("nextCursor");
        }
    }
}
