// <auto-generated>
/*
 * ProgrammableInbox Email Inboxes API
 *
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using ProgrammableInbox.Sdk.Client;

namespace ProgrammableInbox.Sdk.Model
{
    /// <summary>
    /// GetEmailInboxMessages200ResponseDataMessagesInner
    /// </summary>
    public partial class GetEmailInboxMessages200ResponseDataMessagesInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetEmailInboxMessages200ResponseDataMessagesInner" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="threadId">threadId</param>
        /// <param name="subject">subject</param>
        /// <param name="from">from</param>
        /// <param name="to">to</param>
        /// <param name="cc">cc</param>
        /// <param name="bcc">bcc</param>
        /// <param name="text">text</param>
        /// <param name="html">html</param>
        /// <param name="isStarred">isStarred</param>
        /// <param name="isRead">Inbox-wide, not per-user: one shared flag reflecting whether any viewer has opened this message.</param>
        /// <param name="tags">tags</param>
        /// <param name="categories">Categories assigned to the message. Matched by the &#x60;categories&#x60; parameter.</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="parentMessageId">parentMessageId</param>
        /// <param name="bodyText">Plain text of the body, and the field the &#x60;q&#x60; parameter searches. Equal to &#x60;text&#x60; when the sender supplied a text part, otherwise extracted from &#x60;html&#x60;. Null for messages stored before this field existed.</param>
        /// <param name="extractedOtp">One-time code parsed from the message body. Derived from text/html, which the same email_messages:read scope already returns.</param>
        /// <param name="threadCount">Number of messages in the thread (present only in grouped mode)</param>
        [JsonConstructor]
        public GetEmailInboxMessages200ResponseDataMessagesInner(string id, string threadId, string subject, string from, List<string> to, List<string> cc, List<string> bcc, string text, string html, bool isStarred, bool isRead, List<string> tags, List<string> categories, DateTime createdAt, string? parentMessageId = default, string? bodyText = default, string? extractedOtp = default, Option<int?> threadCount = default)
        {
            Id = id;
            ThreadId = threadId;
            Subject = subject;
            From = from;
            To = to;
            Cc = cc;
            Bcc = bcc;
            Text = text;
            Html = html;
            IsStarred = isStarred;
            IsRead = isRead;
            Tags = tags;
            Categories = categories;
            CreatedAt = createdAt;
            ParentMessageId = parentMessageId;
            BodyText = bodyText;
            ExtractedOtp = extractedOtp;
            ThreadCountOption = threadCount;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        /* <example>msg-1</example> */
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets ThreadId
        /// </summary>
        /* <example>thread-1</example> */
        [JsonPropertyName("threadId")]
        public string ThreadId { get; set; }

        /// <summary>
        /// Gets or Sets Subject
        /// </summary>
        /* <example>Support Request</example> */
        [JsonPropertyName("subject")]
        public string Subject { get; set; }

        /// <summary>
        /// Gets or Sets From
        /// </summary>
        /* <example>customer@example.com</example> */
        [JsonPropertyName("from")]
        public string From { get; set; }

        /// <summary>
        /// Gets or Sets To
        /// </summary>
        [JsonPropertyName("to")]
        public List<string> To { get; set; }

        /// <summary>
        /// Gets or Sets Cc
        /// </summary>
        [JsonPropertyName("cc")]
        public List<string> Cc { get; set; }

        /// <summary>
        /// Gets or Sets Bcc
        /// </summary>
        [JsonPropertyName("bcc")]
        public List<string> Bcc { get; set; }

        /// <summary>
        /// Gets or Sets Text
        /// </summary>
        /* <example>Hello, I need help with...</example> */
        [JsonPropertyName("text")]
        public string Text { get; set; }

        /// <summary>
        /// Gets or Sets Html
        /// </summary>
        /* <example>&lt;p&gt;Hello, I need help with...&lt;/p&gt;</example> */
        [JsonPropertyName("html")]
        public string Html { get; set; }

        /// <summary>
        /// Gets or Sets IsStarred
        /// </summary>
        /* <example>false</example> */
        [JsonPropertyName("isStarred")]
        public bool IsStarred { get; set; }

        /// <summary>
        /// Inbox-wide, not per-user: one shared flag reflecting whether any viewer has opened this message.
        /// </summary>
        /// <value>Inbox-wide, not per-user: one shared flag reflecting whether any viewer has opened this message.</value>
        /* <example>false</example> */
        [JsonPropertyName("isRead")]
        public bool IsRead { get; set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [JsonPropertyName("tags")]
        public List<string> Tags { get; set; }

        /// <summary>
        /// Categories assigned to the message. Matched by the &#x60;categories&#x60; parameter.
        /// </summary>
        /// <value>Categories assigned to the message. Matched by the &#x60;categories&#x60; parameter.</value>
        [JsonPropertyName("categories")]
        public List<string> Categories { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("createdAt")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets ParentMessageId
        /// </summary>
        /* <example>msg-0</example> */
        [JsonPropertyName("parentMessageId")]
        public string? ParentMessageId { get; set; }

        /// <summary>
        /// Plain text of the body, and the field the &#x60;q&#x60; parameter searches. Equal to &#x60;text&#x60; when the sender supplied a text part, otherwise extracted from &#x60;html&#x60;. Null for messages stored before this field existed.
        /// </summary>
        /// <value>Plain text of the body, and the field the &#x60;q&#x60; parameter searches. Equal to &#x60;text&#x60; when the sender supplied a text part, otherwise extracted from &#x60;html&#x60;. Null for messages stored before this field existed.</value>
        /* <example>Hello, I need help with...</example> */
        [JsonPropertyName("bodyText")]
        public string? BodyText { get; set; }

        /// <summary>
        /// One-time code parsed from the message body. Derived from text/html, which the same email_messages:read scope already returns.
        /// </summary>
        /// <value>One-time code parsed from the message body. Derived from text/html, which the same email_messages:read scope already returns.</value>
        /* <example>123456</example> */
        [JsonPropertyName("extractedOtp")]
        public string? ExtractedOtp { get; set; }

        /// <summary>
        /// Used to track the state of ThreadCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ThreadCountOption { get; private set; }

        /// <summary>
        /// Number of messages in the thread (present only in grouped mode)
        /// </summary>
        /// <value>Number of messages in the thread (present only in grouped mode)</value>
        [JsonPropertyName("threadCount")]
        public int? ThreadCount { get { return this.ThreadCountOption.Value; } set { this.ThreadCountOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetEmailInboxMessages200ResponseDataMessagesInner {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ThreadId: ").Append(ThreadId).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  From: ").Append(From).Append("\n");
            sb.Append("  To: ").Append(To).Append("\n");
            sb.Append("  Cc: ").Append(Cc).Append("\n");
            sb.Append("  Bcc: ").Append(Bcc).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Html: ").Append(Html).Append("\n");
            sb.Append("  IsStarred: ").Append(IsStarred).Append("\n");
            sb.Append("  IsRead: ").Append(IsRead).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  Categories: ").Append(Categories).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  ParentMessageId: ").Append(ParentMessageId).Append("\n");
            sb.Append("  BodyText: ").Append(BodyText).Append("\n");
            sb.Append("  ExtractedOtp: ").Append(ExtractedOtp).Append("\n");
            sb.Append("  ThreadCount: ").Append(ThreadCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetEmailInboxMessages200ResponseDataMessagesInner" />
    /// </summary>
    public partial class GetEmailInboxMessages200ResponseDataMessagesInnerJsonConverter : JsonConverter<GetEmailInboxMessages200ResponseDataMessagesInner>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="GetEmailInboxMessages200ResponseDataMessagesInnerJsonConverter" /> class.
        /// </summary>
        public GetEmailInboxMessages200ResponseDataMessagesInnerJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public string CreatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="GetEmailInboxMessages200ResponseDataMessagesInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetEmailInboxMessages200ResponseDataMessagesInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> threadId = default;
            Option<string?> subject = default;
            Option<string?> from = default;
            Option<List<string>?> to = default;
            Option<List<string>?> cc = default;
            Option<List<string>?> bcc = default;
            Option<string?> text = default;
            Option<string?> html = default;
            Option<bool?> isStarred = default;
            Option<bool?> isRead = default;
            Option<List<string>?> tags = default;
            Option<List<string>?> categories = default;
            Option<DateTime?> createdAt = default;
            Option<string?> parentMessageId = default;
            Option<string?> bodyText = default;
            Option<string?> extractedOtp = default;
            Option<int?> threadCount = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "threadId":
                            threadId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "subject":
                            subject = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "from":
                            from = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "to":
                            to = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "cc":
                            cc = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "bcc":
                            bcc = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "text":
                            text = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "html":
                            html = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "isStarred":
                            isStarred = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "isRead":
                            isRead = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "tags":
                            tags = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "categories":
                            categories = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "createdAt":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "parentMessageId":
                            parentMessageId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "bodyText":
                            bodyText = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "extractedOtp":
                            extractedOtp = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "threadCount":
                            threadCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class GetEmailInboxMessages200ResponseDataMessagesInner.", nameof(id));

            if (!threadId.IsSet)
                throw new ArgumentException("Property is required for class GetEmailInboxMessages200ResponseDataMessagesInner.", nameof(threadId));

            if (!subject.IsSet)
                throw new ArgumentException("Property is required for class GetEmailInboxMessages200ResponseDataMessagesInner.", nameof(subject));

            if (!from.IsSet)
                throw new ArgumentException("Property is required for class GetEmailInboxMessages200ResponseDataMessagesInner.", nameof(from));

            if (!to.IsSet)
                throw new ArgumentException("Property is required for class GetEmailInboxMessages200ResponseDataMessagesInner.", nameof(to));

            if (!cc.IsSet)
                throw new ArgumentException("Property is required for class GetEmailInboxMessages200ResponseDataMessagesInner.", nameof(cc));

            if (!bcc.IsSet)
                throw new ArgumentException("Property is required for class GetEmailInboxMessages200ResponseDataMessagesInner.", nameof(bcc));

            if (!text.IsSet)
                throw new ArgumentException("Property is required for class GetEmailInboxMessages200ResponseDataMessagesInner.", nameof(text));

            if (!html.IsSet)
                throw new ArgumentException("Property is required for class GetEmailInboxMessages200ResponseDataMessagesInner.", nameof(html));

            if (!isStarred.IsSet)
                throw new ArgumentException("Property is required for class GetEmailInboxMessages200ResponseDataMessagesInner.", nameof(isStarred));

            if (!isRead.IsSet)
                throw new ArgumentException("Property is required for class GetEmailInboxMessages200ResponseDataMessagesInner.", nameof(isRead));

            if (!tags.IsSet)
                throw new ArgumentException("Property is required for class GetEmailInboxMessages200ResponseDataMessagesInner.", nameof(tags));

            if (!categories.IsSet)
                throw new ArgumentException("Property is required for class GetEmailInboxMessages200ResponseDataMessagesInner.", nameof(categories));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class GetEmailInboxMessages200ResponseDataMessagesInner.", nameof(createdAt));

            if (!parentMessageId.IsSet)
                throw new ArgumentException("Property is required for class GetEmailInboxMessages200ResponseDataMessagesInner.", nameof(parentMessageId));

            if (!bodyText.IsSet)
                throw new ArgumentException("Property is required for class GetEmailInboxMessages200ResponseDataMessagesInner.", nameof(bodyText));

            if (!extractedOtp.IsSet)
                throw new ArgumentException("Property is required for class GetEmailInboxMessages200ResponseDataMessagesInner.", nameof(extractedOtp));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class GetEmailInboxMessages200ResponseDataMessagesInner.");

            if (threadId.IsSet && threadId.Value == null)
                throw new ArgumentNullException(nameof(threadId), "Property is not nullable for class GetEmailInboxMessages200ResponseDataMessagesInner.");

            if (subject.IsSet && subject.Value == null)
                throw new ArgumentNullException(nameof(subject), "Property is not nullable for class GetEmailInboxMessages200ResponseDataMessagesInner.");

            if (from.IsSet && from.Value == null)
                throw new ArgumentNullException(nameof(from), "Property is not nullable for class GetEmailInboxMessages200ResponseDataMessagesInner.");

            if (to.IsSet && to.Value == null)
                throw new ArgumentNullException(nameof(to), "Property is not nullable for class GetEmailInboxMessages200ResponseDataMessagesInner.");

            if (cc.IsSet && cc.Value == null)
                throw new ArgumentNullException(nameof(cc), "Property is not nullable for class GetEmailInboxMessages200ResponseDataMessagesInner.");

            if (bcc.IsSet && bcc.Value == null)
                throw new ArgumentNullException(nameof(bcc), "Property is not nullable for class GetEmailInboxMessages200ResponseDataMessagesInner.");

            if (text.IsSet && text.Value == null)
                throw new ArgumentNullException(nameof(text), "Property is not nullable for class GetEmailInboxMessages200ResponseDataMessagesInner.");

            if (html.IsSet && html.Value == null)
                throw new ArgumentNullException(nameof(html), "Property is not nullable for class GetEmailInboxMessages200ResponseDataMessagesInner.");

            if (isStarred.IsSet && isStarred.Value == null)
                throw new ArgumentNullException(nameof(isStarred), "Property is not nullable for class GetEmailInboxMessages200ResponseDataMessagesInner.");

            if (isRead.IsSet && isRead.Value == null)
                throw new ArgumentNullException(nameof(isRead), "Property is not nullable for class GetEmailInboxMessages200ResponseDataMessagesInner.");

            if (tags.IsSet && tags.Value == null)
                throw new ArgumentNullException(nameof(tags), "Property is not nullable for class GetEmailInboxMessages200ResponseDataMessagesInner.");

            if (categories.IsSet && categories.Value == null)
                throw new ArgumentNullException(nameof(categories), "Property is not nullable for class GetEmailInboxMessages200ResponseDataMessagesInner.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class GetEmailInboxMessages200ResponseDataMessagesInner.");

            if (threadCount.IsSet && threadCount.Value == null)
                throw new ArgumentNullException(nameof(threadCount), "Property is not nullable for class GetEmailInboxMessages200ResponseDataMessagesInner.");

            return new GetEmailInboxMessages200ResponseDataMessagesInner(id.Value!, threadId.Value!, subject.Value!, from.Value!, to.Value!, cc.Value!, bcc.Value!, text.Value!, html.Value!, isStarred.Value!.Value!, isRead.Value!.Value!, tags.Value!, categories.Value!, createdAt.Value!.Value!, parentMessageId.Value!, bodyText.Value!, extractedOtp.Value!, threadCount);
        }

        /// <summary>
        /// Serializes a <see cref="GetEmailInboxMessages200ResponseDataMessagesInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getEmailInboxMessages200ResponseDataMessagesInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetEmailInboxMessages200ResponseDataMessagesInner getEmailInboxMessages200ResponseDataMessagesInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getEmailInboxMessages200ResponseDataMessagesInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetEmailInboxMessages200ResponseDataMessagesInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getEmailInboxMessages200ResponseDataMessagesInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetEmailInboxMessages200ResponseDataMessagesInner getEmailInboxMessages200ResponseDataMessagesInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getEmailInboxMessages200ResponseDataMessagesInner.Id == null)
                throw new ArgumentNullException(nameof(getEmailInboxMessages200ResponseDataMessagesInner.Id), "Property is required for class GetEmailInboxMessages200ResponseDataMessagesInner.");

            if (getEmailInboxMessages200ResponseDataMessagesInner.ThreadId == null)
                throw new ArgumentNullException(nameof(getEmailInboxMessages200ResponseDataMessagesInner.ThreadId), "Property is required for class GetEmailInboxMessages200ResponseDataMessagesInner.");

            if (getEmailInboxMessages200ResponseDataMessagesInner.Subject == null)
                throw new ArgumentNullException(nameof(getEmailInboxMessages200ResponseDataMessagesInner.Subject), "Property is required for class GetEmailInboxMessages200ResponseDataMessagesInner.");

            if (getEmailInboxMessages200ResponseDataMessagesInner.From == null)
                throw new ArgumentNullException(nameof(getEmailInboxMessages200ResponseDataMessagesInner.From), "Property is required for class GetEmailInboxMessages200ResponseDataMessagesInner.");

            if (getEmailInboxMessages200ResponseDataMessagesInner.To == null)
                throw new ArgumentNullException(nameof(getEmailInboxMessages200ResponseDataMessagesInner.To), "Property is required for class GetEmailInboxMessages200ResponseDataMessagesInner.");

            if (getEmailInboxMessages200ResponseDataMessagesInner.Cc == null)
                throw new ArgumentNullException(nameof(getEmailInboxMessages200ResponseDataMessagesInner.Cc), "Property is required for class GetEmailInboxMessages200ResponseDataMessagesInner.");

            if (getEmailInboxMessages200ResponseDataMessagesInner.Bcc == null)
                throw new ArgumentNullException(nameof(getEmailInboxMessages200ResponseDataMessagesInner.Bcc), "Property is required for class GetEmailInboxMessages200ResponseDataMessagesInner.");

            if (getEmailInboxMessages200ResponseDataMessagesInner.Text == null)
                throw new ArgumentNullException(nameof(getEmailInboxMessages200ResponseDataMessagesInner.Text), "Property is required for class GetEmailInboxMessages200ResponseDataMessagesInner.");

            if (getEmailInboxMessages200ResponseDataMessagesInner.Html == null)
                throw new ArgumentNullException(nameof(getEmailInboxMessages200ResponseDataMessagesInner.Html), "Property is required for class GetEmailInboxMessages200ResponseDataMessagesInner.");

            if (getEmailInboxMessages200ResponseDataMessagesInner.Tags == null)
                throw new ArgumentNullException(nameof(getEmailInboxMessages200ResponseDataMessagesInner.Tags), "Property is required for class GetEmailInboxMessages200ResponseDataMessagesInner.");

            if (getEmailInboxMessages200ResponseDataMessagesInner.Categories == null)
                throw new ArgumentNullException(nameof(getEmailInboxMessages200ResponseDataMessagesInner.Categories), "Property is required for class GetEmailInboxMessages200ResponseDataMessagesInner.");

            writer.WriteString("id", getEmailInboxMessages200ResponseDataMessagesInner.Id);

            writer.WriteString("threadId", getEmailInboxMessages200ResponseDataMessagesInner.ThreadId);

            writer.WriteString("subject", getEmailInboxMessages200ResponseDataMessagesInner.Subject);

            writer.WriteString("from", getEmailInboxMessages200ResponseDataMessagesInner.From);

            writer.WritePropertyName("to");
            JsonSerializer.Serialize(writer, getEmailInboxMessages200ResponseDataMessagesInner.To, jsonSerializerOptions);
            writer.WritePropertyName("cc");
            JsonSerializer.Serialize(writer, getEmailInboxMessages200ResponseDataMessagesInner.Cc, jsonSerializerOptions);
            writer.WritePropertyName("bcc");
            JsonSerializer.Serialize(writer, getEmailInboxMessages200ResponseDataMessagesInner.Bcc, jsonSerializerOptions);
            writer.WriteString("text", getEmailInboxMessages200ResponseDataMessagesInner.Text);

            writer.WriteString("html", getEmailInboxMessages200ResponseDataMessagesInner.Html);

            writer.WriteBoolean("isStarred", getEmailInboxMessages200ResponseDataMessagesInner.IsStarred);

            writer.WriteBoolean("isRead", getEmailInboxMessages200ResponseDataMessagesInner.IsRead);

            writer.WritePropertyName("tags");
            JsonSerializer.Serialize(writer, getEmailInboxMessages200ResponseDataMessagesInner.Tags, jsonSerializerOptions);
            writer.WritePropertyName("categories");
            JsonSerializer.Serialize(writer, getEmailInboxMessages200ResponseDataMessagesInner.Categories, jsonSerializerOptions);
            writer.WriteString("createdAt", getEmailInboxMessages200ResponseDataMessagesInner.CreatedAt.ToString(CreatedAtFormat));

            if (getEmailInboxMessages200ResponseDataMessagesInner.ParentMessageId != null)
                writer.WriteString("parentMessageId", getEmailInboxMessages200ResponseDataMessagesInner.ParentMessageId);
            else
                writer.WriteNull("parentMessageId");

            if (getEmailInboxMessages200ResponseDataMessagesInner.BodyText != null)
                writer.WriteString("bodyText", getEmailInboxMessages200ResponseDataMessagesInner.BodyText);
            else
                writer.WriteNull("bodyText");

            if (getEmailInboxMessages200ResponseDataMessagesInner.ExtractedOtp != null)
                writer.WriteString("extractedOtp", getEmailInboxMessages200ResponseDataMessagesInner.ExtractedOtp);
            else
                writer.WriteNull("extractedOtp");

            if (getEmailInboxMessages200ResponseDataMessagesInner.ThreadCountOption.IsSet)
                writer.WriteNumber("threadCount", getEmailInboxMessages200ResponseDataMessagesInner.ThreadCountOption.Value!.Value);
        }
    }
}
