// <auto-generated>
/*
 * ProgrammableInbox Email Inboxes API
 *
 * Email inbox management endpoints with API key support
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using ProgrammableInbox.Sdk.Client;

namespace ProgrammableInbox.Sdk.Model
{
    /// <summary>
    /// UpdateEmailInboxRequest
    /// </summary>
    public partial class UpdateEmailInboxRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateEmailInboxRequest" /> class.
        /// </summary>
        /// <param name="name">The new display label. Subject to the impersonation blocklist, so an inbox cannot be renamed into one.</param>
        /// <param name="email">Accepted only when it matches the current address. Present so a client can round-trip a full record; any other value is a 409.</param>
        [JsonConstructor]
        public UpdateEmailInboxRequest(Option<string?> name = default, Option<string?> email = default)
        {
            NameOption = name;
            EmailOption = email;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// The new display label. Subject to the impersonation blocklist, so an inbox cannot be renamed into one.
        /// </summary>
        /// <value>The new display label. Subject to the impersonation blocklist, so an inbox cannot be renamed into one.</value>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Email
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EmailOption { get; private set; }

        /// <summary>
        /// Accepted only when it matches the current address. Present so a client can round-trip a full record; any other value is a 409.
        /// </summary>
        /// <value>Accepted only when it matches the current address. Present so a client can round-trip a full record; any other value is a 409.</value>
        [JsonPropertyName("email")]
        public string? Email { get { return this.EmailOption.Value; } set { this.EmailOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateEmailInboxRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UpdateEmailInboxRequest" />
    /// </summary>
    public partial class UpdateEmailInboxRequestJsonConverter : JsonConverter<UpdateEmailInboxRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateEmailInboxRequestJsonConverter" /> class.
        /// </summary>
        public UpdateEmailInboxRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="UpdateEmailInboxRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UpdateEmailInboxRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> email = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "email":
                            email = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (email.IsSet && email.Value == null)
                throw new ArgumentNullException(nameof(email), "Property is not nullable for class UpdateEmailInboxRequest.");

            return new UpdateEmailInboxRequest(name, email);
        }

        /// <summary>
        /// Serializes a <see cref="UpdateEmailInboxRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateEmailInboxRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UpdateEmailInboxRequest updateEmailInboxRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, updateEmailInboxRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UpdateEmailInboxRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateEmailInboxRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UpdateEmailInboxRequest updateEmailInboxRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (updateEmailInboxRequest.EmailOption.IsSet && updateEmailInboxRequest.Email == null)
                throw new ArgumentNullException(nameof(updateEmailInboxRequest.Email), "Property is required for class UpdateEmailInboxRequest.");

            if (updateEmailInboxRequest.NameOption.IsSet)
                if (updateEmailInboxRequest.NameOption.Value != null)
                    writer.WriteString("name", updateEmailInboxRequest.Name);
                else
                    writer.WriteNull("name");

            if (updateEmailInboxRequest.EmailOption.IsSet)
                writer.WriteString("email", updateEmailInboxRequest.Email);
        }
    }
}
